// vecstore.proto — internal gRPC contract between the Go side (ChunkStore /
// IndexManager) and the C++ vecstore process. Address configured via
// vecstore.grpc_addr in the node config file.
//
// See Stratum_接口设计v9.md "vecstore 内部 gRPC（vecstore.proto）" for the
// authoritative specification this file mirrors exactly.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: vecstore.proto

package vecstore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChunkStorageService_Write_FullMethodName          = "/vecstore.ChunkStorageService/Write"
	ChunkStorageService_Read_FullMethodName           = "/vecstore.ChunkStorageService/Read"
	ChunkStorageService_Exists_FullMethodName         = "/vecstore.ChunkStorageService/Exists"
	ChunkStorageService_Delete_FullMethodName         = "/vecstore.ChunkStorageService/Delete"
	ChunkStorageService_DeleteByPrefix_FullMethodName = "/vecstore.ChunkStorageService/DeleteByPrefix"
	ChunkStorageService_DiskUsage_FullMethodName      = "/vecstore.ChunkStorageService/DiskUsage"
)

// ChunkStorageServiceClient is the client API for ChunkStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChunkStorageServiceClient interface {
	Write(ctx context.Context, in *WriteChunkRequest, opts ...grpc.CallOption) (*WriteChunkResponse, error)
	Read(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (*ReadChunkResponse, error)
	Exists(ctx context.Context, in *ExistsChunkRequest, opts ...grpc.CallOption) (*ExistsChunkResponse, error)
	Delete(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error)
	DeleteByPrefix(ctx context.Context, in *DeleteByPrefixRequest, opts ...grpc.CallOption) (*DeleteByPrefixResponse, error)
	DiskUsage(ctx context.Context, in *DiskUsageRequest, opts ...grpc.CallOption) (*DiskUsageResponse, error)
}

type chunkStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkStorageServiceClient(cc grpc.ClientConnInterface) ChunkStorageServiceClient {
	return &chunkStorageServiceClient{cc}
}

func (c *chunkStorageServiceClient) Write(ctx context.Context, in *WriteChunkRequest, opts ...grpc.CallOption) (*WriteChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteChunkResponse)
	err := c.cc.Invoke(ctx, ChunkStorageService_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkStorageServiceClient) Read(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (*ReadChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadChunkResponse)
	err := c.cc.Invoke(ctx, ChunkStorageService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkStorageServiceClient) Exists(ctx context.Context, in *ExistsChunkRequest, opts ...grpc.CallOption) (*ExistsChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistsChunkResponse)
	err := c.cc.Invoke(ctx, ChunkStorageService_Exists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkStorageServiceClient) Delete(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChunkResponse)
	err := c.cc.Invoke(ctx, ChunkStorageService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkStorageServiceClient) DeleteByPrefix(ctx context.Context, in *DeleteByPrefixRequest, opts ...grpc.CallOption) (*DeleteByPrefixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteByPrefixResponse)
	err := c.cc.Invoke(ctx, ChunkStorageService_DeleteByPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkStorageServiceClient) DiskUsage(ctx context.Context, in *DiskUsageRequest, opts ...grpc.CallOption) (*DiskUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiskUsageResponse)
	err := c.cc.Invoke(ctx, ChunkStorageService_DiskUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChunkStorageServiceServer is the server API for ChunkStorageService service.
// All implementations must embed UnimplementedChunkStorageServiceServer
// for forward compatibility.
type ChunkStorageServiceServer interface {
	Write(context.Context, *WriteChunkRequest) (*WriteChunkResponse, error)
	Read(context.Context, *ReadChunkRequest) (*ReadChunkResponse, error)
	Exists(context.Context, *ExistsChunkRequest) (*ExistsChunkResponse, error)
	Delete(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error)
	DeleteByPrefix(context.Context, *DeleteByPrefixRequest) (*DeleteByPrefixResponse, error)
	DiskUsage(context.Context, *DiskUsageRequest) (*DiskUsageResponse, error)
	mustEmbedUnimplementedChunkStorageServiceServer()
}

// UnimplementedChunkStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChunkStorageServiceServer struct{}

func (UnimplementedChunkStorageServiceServer) Write(context.Context, *WriteChunkRequest) (*WriteChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedChunkStorageServiceServer) Read(context.Context, *ReadChunkRequest) (*ReadChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedChunkStorageServiceServer) Exists(context.Context, *ExistsChunkRequest) (*ExistsChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exists not implemented")
}
func (UnimplementedChunkStorageServiceServer) Delete(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedChunkStorageServiceServer) DeleteByPrefix(context.Context, *DeleteByPrefixRequest) (*DeleteByPrefixResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteByPrefix not implemented")
}
func (UnimplementedChunkStorageServiceServer) DiskUsage(context.Context, *DiskUsageRequest) (*DiskUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiskUsage not implemented")
}
func (UnimplementedChunkStorageServiceServer) mustEmbedUnimplementedChunkStorageServiceServer() {}
func (UnimplementedChunkStorageServiceServer) testEmbeddedByValue()                             {}

// UnsafeChunkStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkStorageServiceServer will
// result in compilation errors.
type UnsafeChunkStorageServiceServer interface {
	mustEmbedUnimplementedChunkStorageServiceServer()
}

func RegisterChunkStorageServiceServer(s grpc.ServiceRegistrar, srv ChunkStorageServiceServer) {
	// If the following call pancis, it indicates UnimplementedChunkStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChunkStorageService_ServiceDesc, srv)
}

func _ChunkStorageService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkStorageServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkStorageService_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkStorageServiceServer).Write(ctx, req.(*WriteChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkStorageService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkStorageServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkStorageService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkStorageServiceServer).Read(ctx, req.(*ReadChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkStorageService_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkStorageServiceServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkStorageService_Exists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkStorageServiceServer).Exists(ctx, req.(*ExistsChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkStorageService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkStorageServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkStorageService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkStorageServiceServer).Delete(ctx, req.(*DeleteChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkStorageService_DeleteByPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkStorageServiceServer).DeleteByPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkStorageService_DeleteByPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkStorageServiceServer).DeleteByPrefix(ctx, req.(*DeleteByPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkStorageService_DiskUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiskUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkStorageServiceServer).DiskUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkStorageService_DiskUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkStorageServiceServer).DiskUsage(ctx, req.(*DiskUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChunkStorageService_ServiceDesc is the grpc.ServiceDesc for ChunkStorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkStorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vecstore.ChunkStorageService",
	HandlerType: (*ChunkStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _ChunkStorageService_Write_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _ChunkStorageService_Read_Handler,
		},
		{
			MethodName: "Exists",
			Handler:    _ChunkStorageService_Exists_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ChunkStorageService_Delete_Handler,
		},
		{
			MethodName: "DeleteByPrefix",
			Handler:    _ChunkStorageService_DeleteByPrefix_Handler,
		},
		{
			MethodName: "DiskUsage",
			Handler:    _ChunkStorageService_DiskUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vecstore.proto",
}

const (
	VectorIndexService_Build_FullMethodName         = "/vecstore.VectorIndexService/Build"
	VectorIndexService_AddChunks_FullMethodName     = "/vecstore.VectorIndexService/AddChunks"
	VectorIndexService_Search_FullMethodName        = "/vecstore.VectorIndexService/Search"
	VectorIndexService_Save_FullMethodName          = "/vecstore.VectorIndexService/Save"
	VectorIndexService_Load_FullMethodName          = "/vecstore.VectorIndexService/Load"
	VectorIndexService_LoadForAppend_FullMethodName = "/vecstore.VectorIndexService/LoadForAppend"
	VectorIndexService_ExistsIndex_FullMethodName   = "/vecstore.VectorIndexService/ExistsIndex"
	VectorIndexService_RemoveChunks_FullMethodName  = "/vecstore.VectorIndexService/RemoveChunks"
	VectorIndexService_Reset_FullMethodName         = "/vecstore.VectorIndexService/Reset"
	VectorIndexService_Drop_FullMethodName          = "/vecstore.VectorIndexService/Drop"
)

// VectorIndexServiceClient is the client API for VectorIndexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VectorIndexServiceClient interface {
	Build(ctx context.Context, in *BuildIndexRequest, opts ...grpc.CallOption) (*BuildIndexResponse, error)
	// AddChunks appends chunk vectors to an index already opened (or created
	// on first call) for (kb_id, version_id). The Go side splits a large
	// build into one Build call followed by one or more AddChunks calls so a
	// single gRPC message never exceeds the default 4 MiB limit.
	AddChunks(ctx context.Context, in *AddChunksRequest, opts ...grpc.CallOption) (*AddChunksResponse, error)
	Search(ctx context.Context, in *SearchIndexRequest, opts ...grpc.CallOption) (*SearchIndexResponse, error)
	Save(ctx context.Context, in *SaveIndexRequest, opts ...grpc.CallOption) (*SaveIndexResponse, error)
	Load(ctx context.Context, in *LoadIndexRequest, opts ...grpc.CallOption) (*LoadIndexResponse, error)
	// LoadForAppend loads a persisted index as the *starting point* of a
	// build rather than as a finished artifact: afterwards the index is in
	// BUILDING state and accepts AddChunks, and a later Save seals it for
	// (kb_id, version_id). This is what makes §8.6(c) incremental reuse
	// possible without changing Faiss usage: HNSW supports appending to a
	// graph that was written and read back, but our own Load deliberately
	// seals the build (BUILDING -> READY), so appending through it is
	// rejected. `path` names the *base* artifact (normally the parent
	// version's index file); the object it is loaded into belongs to
	// (kb_id, version_id), i.e. the version being built.
	LoadForAppend(ctx context.Context, in *LoadIndexForAppendRequest, opts ...grpc.CallOption) (*LoadIndexForAppendResponse, error)
	// ExistsIndex reports whether a persisted index exists at path for
	// (kb_id, version_id): both the Faiss index file and its .ids sidecar
	// must be present for Load to succeed. Stateless — it inspects the
	// filesystem only, so it also answers correctly after this process
	// restarted (the in-memory indexes_ map is empty then). Used by the
	// startup reconcile to derive a version's READY status from disk facts
	// instead of trusting that a build-completion callback was delivered.
	ExistsIndex(ctx context.Context, in *ExistsIndexRequest, opts ...grpc.CallOption) (*ExistsIndexResponse, error)
	// RemoveChunks drops the named chunks' vectors from the index and compacts
	// the storage. Only graph-free shapes can do this: faiss compacts
	// IndexFlatCodes (the *_FLAT family) but cannot repair an HNSW graph, so a
	// graphed index answers FAILED_PRECONDITION. The index must still be open —
	// Save seals a build (BUILDING -> READY), so a sealed index has to be
	// reopened with LoadForAppend before it can be modified. Used by §8.6(c)'s
	// deletion path to drop the vectors a version no longer needs, instead of
	// carrying them as tombstones until a rebuild.
	RemoveChunks(ctx context.Context, in *RemoveChunksRequest, opts ...grpc.CallOption) (*RemoveChunksResponse, error)
	Reset(ctx context.Context, in *ResetIndexRequest, opts ...grpc.CallOption) (*ResetIndexResponse, error)
	// Drop releases the in-memory index object for (kb_id, version_id).
	//
	// Without it the vecstore's index map only ever grows: the Go side's LRU
	// eviction and its Discard path both remove the version from their own view,
	// and nothing told the C++ side to do the same, so a long-running process's
	// RSS tracked the number of versions ever touched instead of the number it is
	// holding (H5 of docs/code-review-2026-09-24.md). Reset is not the same thing:
	// it empties an index but keeps the object alive.
	//
	// Idempotent, and best-effort by design: dropping an index that is not
	// resident — never built here, already dropped, or a process that restarted
	// since — succeeds, because the caller is reclaiming memory it may or may not
	// own. The persisted artifact is untouched: this is memory, not disk.
	Drop(ctx context.Context, in *DropIndexRequest, opts ...grpc.CallOption) (*DropIndexResponse, error)
}

type vectorIndexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVectorIndexServiceClient(cc grpc.ClientConnInterface) VectorIndexServiceClient {
	return &vectorIndexServiceClient{cc}
}

func (c *vectorIndexServiceClient) Build(ctx context.Context, in *BuildIndexRequest, opts ...grpc.CallOption) (*BuildIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildIndexResponse)
	err := c.cc.Invoke(ctx, VectorIndexService_Build_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorIndexServiceClient) AddChunks(ctx context.Context, in *AddChunksRequest, opts ...grpc.CallOption) (*AddChunksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddChunksResponse)
	err := c.cc.Invoke(ctx, VectorIndexService_AddChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorIndexServiceClient) Search(ctx context.Context, in *SearchIndexRequest, opts ...grpc.CallOption) (*SearchIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchIndexResponse)
	err := c.cc.Invoke(ctx, VectorIndexService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorIndexServiceClient) Save(ctx context.Context, in *SaveIndexRequest, opts ...grpc.CallOption) (*SaveIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveIndexResponse)
	err := c.cc.Invoke(ctx, VectorIndexService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorIndexServiceClient) Load(ctx context.Context, in *LoadIndexRequest, opts ...grpc.CallOption) (*LoadIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadIndexResponse)
	err := c.cc.Invoke(ctx, VectorIndexService_Load_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorIndexServiceClient) LoadForAppend(ctx context.Context, in *LoadIndexForAppendRequest, opts ...grpc.CallOption) (*LoadIndexForAppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadIndexForAppendResponse)
	err := c.cc.Invoke(ctx, VectorIndexService_LoadForAppend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorIndexServiceClient) ExistsIndex(ctx context.Context, in *ExistsIndexRequest, opts ...grpc.CallOption) (*ExistsIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistsIndexResponse)
	err := c.cc.Invoke(ctx, VectorIndexService_ExistsIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorIndexServiceClient) RemoveChunks(ctx context.Context, in *RemoveChunksRequest, opts ...grpc.CallOption) (*RemoveChunksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveChunksResponse)
	err := c.cc.Invoke(ctx, VectorIndexService_RemoveChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorIndexServiceClient) Reset(ctx context.Context, in *ResetIndexRequest, opts ...grpc.CallOption) (*ResetIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetIndexResponse)
	err := c.cc.Invoke(ctx, VectorIndexService_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorIndexServiceClient) Drop(ctx context.Context, in *DropIndexRequest, opts ...grpc.CallOption) (*DropIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropIndexResponse)
	err := c.cc.Invoke(ctx, VectorIndexService_Drop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VectorIndexServiceServer is the server API for VectorIndexService service.
// All implementations must embed UnimplementedVectorIndexServiceServer
// for forward compatibility.
type VectorIndexServiceServer interface {
	Build(context.Context, *BuildIndexRequest) (*BuildIndexResponse, error)
	// AddChunks appends chunk vectors to an index already opened (or created
	// on first call) for (kb_id, version_id). The Go side splits a large
	// build into one Build call followed by one or more AddChunks calls so a
	// single gRPC message never exceeds the default 4 MiB limit.
	AddChunks(context.Context, *AddChunksRequest) (*AddChunksResponse, error)
	Search(context.Context, *SearchIndexRequest) (*SearchIndexResponse, error)
	Save(context.Context, *SaveIndexRequest) (*SaveIndexResponse, error)
	Load(context.Context, *LoadIndexRequest) (*LoadIndexResponse, error)
	// LoadForAppend loads a persisted index as the *starting point* of a
	// build rather than as a finished artifact: afterwards the index is in
	// BUILDING state and accepts AddChunks, and a later Save seals it for
	// (kb_id, version_id). This is what makes §8.6(c) incremental reuse
	// possible without changing Faiss usage: HNSW supports appending to a
	// graph that was written and read back, but our own Load deliberately
	// seals the build (BUILDING -> READY), so appending through it is
	// rejected. `path` names the *base* artifact (normally the parent
	// version's index file); the object it is loaded into belongs to
	// (kb_id, version_id), i.e. the version being built.
	LoadForAppend(context.Context, *LoadIndexForAppendRequest) (*LoadIndexForAppendResponse, error)
	// ExistsIndex reports whether a persisted index exists at path for
	// (kb_id, version_id): both the Faiss index file and its .ids sidecar
	// must be present for Load to succeed. Stateless — it inspects the
	// filesystem only, so it also answers correctly after this process
	// restarted (the in-memory indexes_ map is empty then). Used by the
	// startup reconcile to derive a version's READY status from disk facts
	// instead of trusting that a build-completion callback was delivered.
	ExistsIndex(context.Context, *ExistsIndexRequest) (*ExistsIndexResponse, error)
	// RemoveChunks drops the named chunks' vectors from the index and compacts
	// the storage. Only graph-free shapes can do this: faiss compacts
	// IndexFlatCodes (the *_FLAT family) but cannot repair an HNSW graph, so a
	// graphed index answers FAILED_PRECONDITION. The index must still be open —
	// Save seals a build (BUILDING -> READY), so a sealed index has to be
	// reopened with LoadForAppend before it can be modified. Used by §8.6(c)'s
	// deletion path to drop the vectors a version no longer needs, instead of
	// carrying them as tombstones until a rebuild.
	RemoveChunks(context.Context, *RemoveChunksRequest) (*RemoveChunksResponse, error)
	Reset(context.Context, *ResetIndexRequest) (*ResetIndexResponse, error)
	// Drop releases the in-memory index object for (kb_id, version_id).
	//
	// Without it the vecstore's index map only ever grows: the Go side's LRU
	// eviction and its Discard path both remove the version from their own view,
	// and nothing told the C++ side to do the same, so a long-running process's
	// RSS tracked the number of versions ever touched instead of the number it is
	// holding (H5 of docs/code-review-2026-09-24.md). Reset is not the same thing:
	// it empties an index but keeps the object alive.
	//
	// Idempotent, and best-effort by design: dropping an index that is not
	// resident — never built here, already dropped, or a process that restarted
	// since — succeeds, because the caller is reclaiming memory it may or may not
	// own. The persisted artifact is untouched: this is memory, not disk.
	Drop(context.Context, *DropIndexRequest) (*DropIndexResponse, error)
	mustEmbedUnimplementedVectorIndexServiceServer()
}

// UnimplementedVectorIndexServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVectorIndexServiceServer struct{}

func (UnimplementedVectorIndexServiceServer) Build(context.Context, *BuildIndexRequest) (*BuildIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Build not implemented")
}
func (UnimplementedVectorIndexServiceServer) AddChunks(context.Context, *AddChunksRequest) (*AddChunksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddChunks not implemented")
}
func (UnimplementedVectorIndexServiceServer) Search(context.Context, *SearchIndexRequest) (*SearchIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedVectorIndexServiceServer) Save(context.Context, *SaveIndexRequest) (*SaveIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedVectorIndexServiceServer) Load(context.Context, *LoadIndexRequest) (*LoadIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Load not implemented")
}
func (UnimplementedVectorIndexServiceServer) LoadForAppend(context.Context, *LoadIndexForAppendRequest) (*LoadIndexForAppendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadForAppend not implemented")
}
func (UnimplementedVectorIndexServiceServer) ExistsIndex(context.Context, *ExistsIndexRequest) (*ExistsIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExistsIndex not implemented")
}
func (UnimplementedVectorIndexServiceServer) RemoveChunks(context.Context, *RemoveChunksRequest) (*RemoveChunksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveChunks not implemented")
}
func (UnimplementedVectorIndexServiceServer) Reset(context.Context, *ResetIndexRequest) (*ResetIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedVectorIndexServiceServer) Drop(context.Context, *DropIndexRequest) (*DropIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Drop not implemented")
}
func (UnimplementedVectorIndexServiceServer) mustEmbedUnimplementedVectorIndexServiceServer() {}
func (UnimplementedVectorIndexServiceServer) testEmbeddedByValue()                            {}

// UnsafeVectorIndexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VectorIndexServiceServer will
// result in compilation errors.
type UnsafeVectorIndexServiceServer interface {
	mustEmbedUnimplementedVectorIndexServiceServer()
}

func RegisterVectorIndexServiceServer(s grpc.ServiceRegistrar, srv VectorIndexServiceServer) {
	// If the following call pancis, it indicates UnimplementedVectorIndexServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VectorIndexService_ServiceDesc, srv)
}

func _VectorIndexService_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorIndexServiceServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorIndexService_Build_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorIndexServiceServer).Build(ctx, req.(*BuildIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorIndexService_AddChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorIndexServiceServer).AddChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorIndexService_AddChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorIndexServiceServer).AddChunks(ctx, req.(*AddChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorIndexService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorIndexServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorIndexService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorIndexServiceServer).Search(ctx, req.(*SearchIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorIndexService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorIndexServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorIndexService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorIndexServiceServer).Save(ctx, req.(*SaveIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorIndexService_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorIndexServiceServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorIndexService_Load_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorIndexServiceServer).Load(ctx, req.(*LoadIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorIndexService_LoadForAppend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadIndexForAppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorIndexServiceServer).LoadForAppend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorIndexService_LoadForAppend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorIndexServiceServer).LoadForAppend(ctx, req.(*LoadIndexForAppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorIndexService_ExistsIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorIndexServiceServer).ExistsIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorIndexService_ExistsIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorIndexServiceServer).ExistsIndex(ctx, req.(*ExistsIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorIndexService_RemoveChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorIndexServiceServer).RemoveChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorIndexService_RemoveChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorIndexServiceServer).RemoveChunks(ctx, req.(*RemoveChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorIndexService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorIndexServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorIndexService_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorIndexServiceServer).Reset(ctx, req.(*ResetIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorIndexService_Drop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorIndexServiceServer).Drop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorIndexService_Drop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorIndexServiceServer).Drop(ctx, req.(*DropIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VectorIndexService_ServiceDesc is the grpc.ServiceDesc for VectorIndexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VectorIndexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vecstore.VectorIndexService",
	HandlerType: (*VectorIndexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Build",
			Handler:    _VectorIndexService_Build_Handler,
		},
		{
			MethodName: "AddChunks",
			Handler:    _VectorIndexService_AddChunks_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _VectorIndexService_Search_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _VectorIndexService_Save_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _VectorIndexService_Load_Handler,
		},
		{
			MethodName: "LoadForAppend",
			Handler:    _VectorIndexService_LoadForAppend_Handler,
		},
		{
			MethodName: "ExistsIndex",
			Handler:    _VectorIndexService_ExistsIndex_Handler,
		},
		{
			MethodName: "RemoveChunks",
			Handler:    _VectorIndexService_RemoveChunks_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _VectorIndexService_Reset_Handler,
		},
		{
			MethodName: "Drop",
			Handler:    _VectorIndexService_Drop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vecstore.proto",
}
