// vecstore.proto — internal gRPC contract between the Go side (ChunkStore /
// IndexManager) and the C++ vecstore process. Address configured via
// vecstore.grpc_addr in the node config file.
//
// See Stratum_接口设计v9.md "vecstore 内部 gRPC（vecstore.proto）" for the
// authoritative specification this file mirrors exactly.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: vecstore.proto

package vecstore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChunkStorageService_Write_FullMethodName          = "/vecstore.ChunkStorageService/Write"
	ChunkStorageService_Read_FullMethodName           = "/vecstore.ChunkStorageService/Read"
	ChunkStorageService_Exists_FullMethodName         = "/vecstore.ChunkStorageService/Exists"
	ChunkStorageService_Delete_FullMethodName         = "/vecstore.ChunkStorageService/Delete"
	ChunkStorageService_DeleteByPrefix_FullMethodName = "/vecstore.ChunkStorageService/DeleteByPrefix"
)

// ChunkStorageServiceClient is the client API for ChunkStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChunkStorageServiceClient interface {
	Write(ctx context.Context, in *WriteChunkRequest, opts ...grpc.CallOption) (*WriteChunkResponse, error)
	Read(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (*ReadChunkResponse, error)
	Exists(ctx context.Context, in *ExistsChunkRequest, opts ...grpc.CallOption) (*ExistsChunkResponse, error)
	Delete(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error)
	DeleteByPrefix(ctx context.Context, in *DeleteByPrefixRequest, opts ...grpc.CallOption) (*DeleteByPrefixResponse, error)
}

type chunkStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkStorageServiceClient(cc grpc.ClientConnInterface) ChunkStorageServiceClient {
	return &chunkStorageServiceClient{cc}
}

func (c *chunkStorageServiceClient) Write(ctx context.Context, in *WriteChunkRequest, opts ...grpc.CallOption) (*WriteChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteChunkResponse)
	err := c.cc.Invoke(ctx, ChunkStorageService_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkStorageServiceClient) Read(ctx context.Context, in *ReadChunkRequest, opts ...grpc.CallOption) (*ReadChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadChunkResponse)
	err := c.cc.Invoke(ctx, ChunkStorageService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkStorageServiceClient) Exists(ctx context.Context, in *ExistsChunkRequest, opts ...grpc.CallOption) (*ExistsChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistsChunkResponse)
	err := c.cc.Invoke(ctx, ChunkStorageService_Exists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkStorageServiceClient) Delete(ctx context.Context, in *DeleteChunkRequest, opts ...grpc.CallOption) (*DeleteChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChunkResponse)
	err := c.cc.Invoke(ctx, ChunkStorageService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkStorageServiceClient) DeleteByPrefix(ctx context.Context, in *DeleteByPrefixRequest, opts ...grpc.CallOption) (*DeleteByPrefixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteByPrefixResponse)
	err := c.cc.Invoke(ctx, ChunkStorageService_DeleteByPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChunkStorageServiceServer is the server API for ChunkStorageService service.
// All implementations must embed UnimplementedChunkStorageServiceServer
// for forward compatibility.
type ChunkStorageServiceServer interface {
	Write(context.Context, *WriteChunkRequest) (*WriteChunkResponse, error)
	Read(context.Context, *ReadChunkRequest) (*ReadChunkResponse, error)
	Exists(context.Context, *ExistsChunkRequest) (*ExistsChunkResponse, error)
	Delete(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error)
	DeleteByPrefix(context.Context, *DeleteByPrefixRequest) (*DeleteByPrefixResponse, error)
	mustEmbedUnimplementedChunkStorageServiceServer()
}

// UnimplementedChunkStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChunkStorageServiceServer struct{}

func (UnimplementedChunkStorageServiceServer) Write(context.Context, *WriteChunkRequest) (*WriteChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedChunkStorageServiceServer) Read(context.Context, *ReadChunkRequest) (*ReadChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedChunkStorageServiceServer) Exists(context.Context, *ExistsChunkRequest) (*ExistsChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exists not implemented")
}
func (UnimplementedChunkStorageServiceServer) Delete(context.Context, *DeleteChunkRequest) (*DeleteChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedChunkStorageServiceServer) DeleteByPrefix(context.Context, *DeleteByPrefixRequest) (*DeleteByPrefixResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteByPrefix not implemented")
}
func (UnimplementedChunkStorageServiceServer) mustEmbedUnimplementedChunkStorageServiceServer() {}
func (UnimplementedChunkStorageServiceServer) testEmbeddedByValue()                             {}

// UnsafeChunkStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkStorageServiceServer will
// result in compilation errors.
type UnsafeChunkStorageServiceServer interface {
	mustEmbedUnimplementedChunkStorageServiceServer()
}

func RegisterChunkStorageServiceServer(s grpc.ServiceRegistrar, srv ChunkStorageServiceServer) {
	// If the following call pancis, it indicates UnimplementedChunkStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChunkStorageService_ServiceDesc, srv)
}

func _ChunkStorageService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkStorageServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkStorageService_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkStorageServiceServer).Write(ctx, req.(*WriteChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkStorageService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkStorageServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkStorageService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkStorageServiceServer).Read(ctx, req.(*ReadChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkStorageService_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkStorageServiceServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkStorageService_Exists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkStorageServiceServer).Exists(ctx, req.(*ExistsChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkStorageService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkStorageServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkStorageService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkStorageServiceServer).Delete(ctx, req.(*DeleteChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkStorageService_DeleteByPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkStorageServiceServer).DeleteByPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkStorageService_DeleteByPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkStorageServiceServer).DeleteByPrefix(ctx, req.(*DeleteByPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChunkStorageService_ServiceDesc is the grpc.ServiceDesc for ChunkStorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkStorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vecstore.ChunkStorageService",
	HandlerType: (*ChunkStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _ChunkStorageService_Write_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _ChunkStorageService_Read_Handler,
		},
		{
			MethodName: "Exists",
			Handler:    _ChunkStorageService_Exists_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ChunkStorageService_Delete_Handler,
		},
		{
			MethodName: "DeleteByPrefix",
			Handler:    _ChunkStorageService_DeleteByPrefix_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vecstore.proto",
}

const (
	VectorIndexService_Build_FullMethodName  = "/vecstore.VectorIndexService/Build"
	VectorIndexService_Search_FullMethodName = "/vecstore.VectorIndexService/Search"
	VectorIndexService_Save_FullMethodName   = "/vecstore.VectorIndexService/Save"
	VectorIndexService_Load_FullMethodName   = "/vecstore.VectorIndexService/Load"
	VectorIndexService_Reset_FullMethodName  = "/vecstore.VectorIndexService/Reset"
)

// VectorIndexServiceClient is the client API for VectorIndexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VectorIndexServiceClient interface {
	Build(ctx context.Context, in *BuildIndexRequest, opts ...grpc.CallOption) (*BuildIndexResponse, error)
	Search(ctx context.Context, in *SearchIndexRequest, opts ...grpc.CallOption) (*SearchIndexResponse, error)
	Save(ctx context.Context, in *SaveIndexRequest, opts ...grpc.CallOption) (*SaveIndexResponse, error)
	Load(ctx context.Context, in *LoadIndexRequest, opts ...grpc.CallOption) (*LoadIndexResponse, error)
	Reset(ctx context.Context, in *ResetIndexRequest, opts ...grpc.CallOption) (*ResetIndexResponse, error)
}

type vectorIndexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVectorIndexServiceClient(cc grpc.ClientConnInterface) VectorIndexServiceClient {
	return &vectorIndexServiceClient{cc}
}

func (c *vectorIndexServiceClient) Build(ctx context.Context, in *BuildIndexRequest, opts ...grpc.CallOption) (*BuildIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildIndexResponse)
	err := c.cc.Invoke(ctx, VectorIndexService_Build_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorIndexServiceClient) Search(ctx context.Context, in *SearchIndexRequest, opts ...grpc.CallOption) (*SearchIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchIndexResponse)
	err := c.cc.Invoke(ctx, VectorIndexService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorIndexServiceClient) Save(ctx context.Context, in *SaveIndexRequest, opts ...grpc.CallOption) (*SaveIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveIndexResponse)
	err := c.cc.Invoke(ctx, VectorIndexService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorIndexServiceClient) Load(ctx context.Context, in *LoadIndexRequest, opts ...grpc.CallOption) (*LoadIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadIndexResponse)
	err := c.cc.Invoke(ctx, VectorIndexService_Load_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorIndexServiceClient) Reset(ctx context.Context, in *ResetIndexRequest, opts ...grpc.CallOption) (*ResetIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetIndexResponse)
	err := c.cc.Invoke(ctx, VectorIndexService_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VectorIndexServiceServer is the server API for VectorIndexService service.
// All implementations must embed UnimplementedVectorIndexServiceServer
// for forward compatibility.
type VectorIndexServiceServer interface {
	Build(context.Context, *BuildIndexRequest) (*BuildIndexResponse, error)
	Search(context.Context, *SearchIndexRequest) (*SearchIndexResponse, error)
	Save(context.Context, *SaveIndexRequest) (*SaveIndexResponse, error)
	Load(context.Context, *LoadIndexRequest) (*LoadIndexResponse, error)
	Reset(context.Context, *ResetIndexRequest) (*ResetIndexResponse, error)
	mustEmbedUnimplementedVectorIndexServiceServer()
}

// UnimplementedVectorIndexServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVectorIndexServiceServer struct{}

func (UnimplementedVectorIndexServiceServer) Build(context.Context, *BuildIndexRequest) (*BuildIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Build not implemented")
}
func (UnimplementedVectorIndexServiceServer) Search(context.Context, *SearchIndexRequest) (*SearchIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedVectorIndexServiceServer) Save(context.Context, *SaveIndexRequest) (*SaveIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedVectorIndexServiceServer) Load(context.Context, *LoadIndexRequest) (*LoadIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Load not implemented")
}
func (UnimplementedVectorIndexServiceServer) Reset(context.Context, *ResetIndexRequest) (*ResetIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedVectorIndexServiceServer) mustEmbedUnimplementedVectorIndexServiceServer() {}
func (UnimplementedVectorIndexServiceServer) testEmbeddedByValue()                            {}

// UnsafeVectorIndexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VectorIndexServiceServer will
// result in compilation errors.
type UnsafeVectorIndexServiceServer interface {
	mustEmbedUnimplementedVectorIndexServiceServer()
}

func RegisterVectorIndexServiceServer(s grpc.ServiceRegistrar, srv VectorIndexServiceServer) {
	// If the following call pancis, it indicates UnimplementedVectorIndexServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VectorIndexService_ServiceDesc, srv)
}

func _VectorIndexService_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorIndexServiceServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorIndexService_Build_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorIndexServiceServer).Build(ctx, req.(*BuildIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorIndexService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorIndexServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorIndexService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorIndexServiceServer).Search(ctx, req.(*SearchIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorIndexService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorIndexServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorIndexService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorIndexServiceServer).Save(ctx, req.(*SaveIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorIndexService_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorIndexServiceServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorIndexService_Load_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorIndexServiceServer).Load(ctx, req.(*LoadIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorIndexService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorIndexServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorIndexService_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorIndexServiceServer).Reset(ctx, req.(*ResetIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VectorIndexService_ServiceDesc is the grpc.ServiceDesc for VectorIndexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VectorIndexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vecstore.VectorIndexService",
	HandlerType: (*VectorIndexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Build",
			Handler:    _VectorIndexService_Build_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _VectorIndexService_Search_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _VectorIndexService_Save_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _VectorIndexService_Load_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _VectorIndexService_Reset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vecstore.proto",
}
