#!/usr/bin/env bash
# docker-cluster.sh — Stratum 多节点 Docker 集群启动/管理脚本
#
# 用原生 docker CLI 管理 N 个 Stratum 节点（不依赖 docker-compose）：
#   - 动态生成每个节点的 YAML 配置（peers 表自动包含全部节点）
#   - 统一管理 Docker 网络、命名数据卷、端口映射（gRPC/raft/metrics）
#   - 幂等：重复执行不会重复创建容器/配置；已存在的容器被复用
#   - 内置健康检查（容器级 healthcheck + leader 选举等待）
#
# 依赖：
#   - docker（可用 docker daemon）
#   - go 1.24+（仅 build 命令需要）
#
# 用法:
#   scripts/docker-cluster.sh <command> [options]
#
# 命令:
#   build                      构建二进制与 Docker 镜像
#   update [N]                 更新集群：重新编译 → 重建镜像 → --force 重建
#                              全部节点容器（数据卷保留，一条命令跑上最新代码）
#   init [N]                   初始化 N 节点配置与网络（幂等，不启动）
#   up [N]                     init + 启动 N 节点（幂等，默认等待 leader）
#   start [node...]            启动节点（默认全部）
#   stop [node...]             停止节点（默认全部）
#   restart [node...]          重启节点（默认全部）
#   status                     查看集群状态与 leader
#   logs [node]                查看节点日志（默认全部，-f 跟踪）
#   embed start|stop|status    管理可选 mock-embed 依赖容器
#   down                       停止并删除容器（保留数据卷）
#   clean                      down + 删除数据卷/网络/配置（完全清理）
#   help                       显示帮助
#
# 选项:
#   --nodes N      集群节点数（默认 3）
#   --base-port P  第一个节点的 gRPC 宿主端口（默认 17000；raft 端口 = P+1000，metrics = P+2000）
#   --network N    Docker 网络名（默认 stratum-net）
#   --image IMG    stratum 镜像名（默认 stratum-node:latest）
#   --force        重建已存在的容器/配置（配合 init/up 使用）
#   --with-embed   同时启动 mock-embed 依赖容器（配合 up 使用）

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUN_DIR="$ROOT/run/docker"
NODES_DIR="$RUN_DIR/nodes"
LOG_DIR="$RUN_DIR/log"
mkdir -p "$NODES_DIR" "$LOG_DIR"

DEFAULT_NODES=3
BASE_PORT=17000
NETWORK=stratum-net
IMAGE=stratum-node:latest
CONTAINER_PREFIX=stratum-node
WITH_EMBED=0
FORCE=0

# ---------- 基础工具函数 ----------

log()  { echo -e "\033[1;36m[docker-cluster]\033[0m $*"; }
warn() { echo -e "\033[1;33m[docker-cluster]\033[0m $*" >&2; }
die()  { echo -e "\033[1;31m[docker-cluster]\033[0m 错误：$*" >&2; exit 1; }

node_name() { echo "${CONTAINER_PREFIX}${1}"; }
node_cfg()  { echo "$NODES_DIR/node${1}/config.yaml"; }

# 容器是否已存在
container_exists() { docker inspect "$1" >/dev/null 2>&1; }

# 节点最后一次当选 leader 时的 term（从未当选则输出 0）。
# raft 语义：集群中当前 leader 一定是「最后一次当选 term」最大的运行中节点，
# 旧 term 的 leader 收到更高 term 的心跳/投票响应后会退位。
node_leader_term() {
  local t
  t="$(docker logs "$1" 2>&1 | grep -o '"became leader"[^}]*' | tail -1 | grep -o 'term":[0-9]*' | cut -d: -f2 || true)"
  echo "${t:-0}"
}

# 输出当前 leader 的容器名（无则输出空）
current_leader() {
  local count=$1 name t max=0 leader=""
  for ((id=1; id<=count; id++)); do
    name="$(node_name "$id")"
    if container_exists "$name" && [[ "$(docker inspect -f '{{.State.Status}}' "$name")" == "running" ]]; then
      t="$(node_leader_term "$name")"
      if [[ "$t" -gt "$max" ]]; then max=$t; leader="$name"; fi
    fi
  done
  [[ "$max" -gt 0 ]] && echo "$leader"
}

# ---------- 1. 构建 ----------

cmd_build() {
  log "构建静态二进制（stratum / mock-embed）…"
  (cd "$ROOT" && CGO_ENABLED=0 go build -o integration/docker/stratum ./cmd/stratum/)
  (cd "$ROOT" && CGO_ENABLED=0 go build -o integration/docker/mock-embed ./integration/docker/mock_embed_server.go)
  log "构建 Docker 镜像 $IMAGE …"
  docker build -t "$IMAGE" -f "$ROOT/integration/docker/Dockerfile" "$ROOT"
  log "构建完成：$IMAGE"
}

# ---------- 2. 网络与配置 ----------

ensure_network() {
  docker network inspect "$NETWORK" >/dev/null 2>&1 || {
    log "创建 Docker 网络 $NETWORK …"
    docker network create "$NETWORK" >/dev/null
  }
}

# 生成节点 id 的配置：node_id、端口、完整 peers 表、Docker 友好 raft 定时
# （200ms 心跳 / [2s,4s) 选举超时，规避 Docker 网络下的 split-vote）。
gen_node_config() {
  local id=$1 count=$2
  local cfg
  cfg="$(node_cfg "$id")"
  mkdir -p "$(dirname "$cfg")"
  cat > "$cfg" <<EOF
# Stratum node $id of ${count}-node cluster — generated by scripts/docker-cluster.sh
node:
  node_id: $id
  grpc_addr: "0.0.0.0:7000"
  raft_addr: "0.0.0.0:8000"
  metrics_addr: "0.0.0.0:9000"

raft:
  heartbeat_interval_ms: 200
  election_timeout_min_ms: 2000
  election_timeout_max_ms: 4000
  peers:
$(for ((p=1; p<=count; p++)); do
    printf '    - id: %s\n      addr: "%s:8000"\n      service_addr: "%s:7000"\n' \
      "$p" "$(node_name "$p")" "$(node_name "$p")"
  done)

storage:
  data_dir: "/var/lib/stratum/node${id}"

vecstore:
  grpc_addr: "host.docker.internal:7100"

embed:
  service_addr: "http://host.docker.internal:8080"

index_manager:
  lru_capacity: 16
  memory_threshold_mb: 4096
  load_wait_timeout_ms: 5000
  callback_max_retries: 3
  callback_retry_base_interval_ms: 200

write_coordinator:
  max_retries: 3
  retry_base_interval_ms: 100

delete_coordinator:
  max_retries: 5
  retry_base_interval_ms: 500

logging:
  level: "info"
EOF
}

cmd_init() {
  local count=${1:-$DEFAULT_NODES}
  ensure_network
  for ((i=1; i<=count; i++)); do
    local cfg
    cfg="$(node_cfg "$i")"
    if [[ -f "$cfg" ]] && [[ "$FORCE" -eq 0 ]]; then
      log "配置已存在，跳过：$cfg（--force 覆盖）"
    else
      gen_node_config "$i" "$count"
      log "生成配置：$cfg"
    fi
  done
  log "已就绪 ${count} 节点配置（网络 $NETWORK）"
}

# ---------- 3. 容器生命周期 ----------

# 从已生成的配置目录推断集群规模（node1…nodeN）
count_from_config() {
  ls "$NODES_DIR" 2>/dev/null | sed -n 's/^node\([0-9]\+\)$/\1/p' | sort -n | tail -1
}

# 启动（或复用/拉起）单个节点容器
run_node() {
  local id=$1
  local name
  name="$(node_name "$id")"
  local gport=$((BASE_PORT + id - 1))
  local rport=$((BASE_PORT + 1000 + id - 1))
  local mport=$((BASE_PORT + 2000 + id - 1))
  local vol="stratum-node${id}-data"

  if container_exists "$name"; then
    if [[ "$FORCE" -eq 1 ]]; then
      log "删除旧容器 $name（--force 重建）…"
      docker rm -f "$name" >/dev/null
    else
      docker start "$name" >/dev/null
      log "复用已存在的容器 $name"
      return
    fi
  fi

  log "启动 $name（gRPC :$gport / raft :$rport / metrics :$mport）…"
  docker run -d --name "$name" \
    --network "$NETWORK" \
    -p "${gport}:7000" -p "${rport}:8000" -p "${mport}:9000" \
    -v "$(node_cfg "$id"):/etc/stratum/config.yaml:ro" \
    -v "${vol}:/var/lib/stratum/node${id}" \
    --add-host host.docker.internal:host-gateway \
    --restart unless-stopped \
    --health-cmd "nc -z -w2 127.0.0.1 7000" \
    --health-interval 5s --health-timeout 2s --health-retries 6 \
    "$IMAGE" >/dev/null
}

# 解析节点 id 列表：无参数时返回全部已配置节点
resolve_node_ids() {
  local count
  count="$(count_from_config)"
  if [[ $# -eq 0 ]]; then
    [[ -n "$count" ]] && seq 1 "$count"
  else
    printf '%s\n' "$@"
  fi
}

cmd_start() {
  local ids
  ids="$(resolve_node_ids "$@")"
  local id
  for id in $ids; do run_node "$id"; done
}

cmd_stop() {
  local ids
  ids="$(resolve_node_ids "$@")"
  local id
  for id in $ids; do
    local name
    name="$(node_name "$id")"
    container_exists "$name" && { docker stop "$name" >/dev/null && log "停止 $name"; }
  done
}

cmd_restart() {
  cmd_stop "$@"
  cmd_start "$@"
}

# 等待 leader 选举稳定（同一节点连续两次以最大 term 出现视为稳定）
wait_for_leader() {
  local count=$1 timeout=${2:-60}
  log "等待 leader 选举（最多 ${timeout}s）…"
  local prev_leader="" prev_term=0 cur_leader="" cur_term=0 id name t
  for _ in $(seq 1 "$timeout"); do
    cur_leader="$(current_leader "$count")"
    cur_term=0
    if [[ -n "$cur_leader" ]]; then
      cur_term="$(node_leader_term "$cur_leader")"
    fi
    if [[ -n "$cur_leader" && "$cur_leader" == "$prev_leader" && "$cur_term" -eq "$prev_term" && "$cur_term" -gt 0 ]]; then
      log "leader 已选出：$cur_leader（term $cur_term）"
      return 0
    fi
    prev_leader="$cur_leader"
    prev_term="$cur_term"
    sleep 1
  done
  warn "等待 leader 超时（${timeout}s）；可用 'logs' 查看各节点日志"
  return 1
}

cmd_up() {
  local count=${1:-$DEFAULT_NODES}
  cmd_init "$count"
  # 启动全部节点（幂等）
  local id
  for ((id=1; id<=count; id++)); do run_node "$id"; done
  if [[ "$WITH_EMBED" -eq 1 ]]; then embed_start; fi
  wait_for_leader "$count"
  cmd_status "$count"
}

# 等待全部节点 running + healthy
wait_healthy() {
  local count=$1 timeout=${2:-90}
  for _ in $(seq 1 "$timeout"); do
    local all_healthy=1 id name st h
    for ((id=1; id<=count; id++)); do
      name="$(node_name "$id")"
      if ! container_exists "$name"; then all_healthy=0; break; fi
      st="$(docker inspect -f '{{.State.Status}}' "$name")"
      h="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$name" 2>/dev/null || echo none)"
      if [[ "$st" != "running" || "$h" != "healthy" ]]; then all_healthy=0; break; fi
    done
    if [[ "$all_healthy" -eq 1 ]]; then
      log "全部 ${count} 个节点 healthy"
      return 0
    fi
    sleep 2
  done
  warn "等待全部节点 healthy 超时（${timeout}s）"
  return 1
}

# update：重新编译 → 重建镜像 → --force 重建全部容器（数据卷保留）。
# 一条命令让集群跑上最新代码；等价于 build + up N --force。
cmd_update() {
  local count=${1:-$DEFAULT_NODES}
  log "== 更新 docker 集群（编译 → 镜像 → 重建容器，数据卷保留）=="
  cmd_build
  FORCE=1
  cmd_up "$count"
  wait_healthy "$count"
  log "更新完成：${count} 个节点已运行最新实现"
}

cmd_down() {
  # 按前缀匹配删除所有 stratum 节点容器
  local ids
  ids="$(docker ps -aq --filter "name=^/${CONTAINER_PREFIX}" 2>/dev/null || true)"
  if [[ -n "$ids" ]]; then
    docker rm -f $ids >/dev/null
    log "已删除容器：$ids"
  else
    log "没有需要删除的节点容器"
  fi
}

cmd_clean() {
  cmd_down
  docker rm -f "stratum-embed" >/dev/null 2>&1 || true
  # 删除命名数据卷
  for id in $(seq 1 32); do
    local vol="stratum-node${id}-data"
    docker volume rm "$vol" >/dev/null 2>&1 && log "删除数据卷 $vol"
  done
  docker network rm "$NETWORK" >/dev/null 2>&1 && log "删除网络 $NETWORK" || true
  if [[ -d "$RUN_DIR" ]]; then
    rm -rf "$RUN_DIR"
    log "删除运行时目录 $RUN_DIR"
  fi
  log "清理完成"
}

# ---------- 4. 状态与日志 ----------

cmd_status() {
  local count=${1:-$DEFAULT_NODES}
  local leader
  leader="$(current_leader "$count")"

  # --json：输出机器可读状态（供控制台 /ops/docker/status 使用）
  if [[ "$JSON_MODE" -eq 1 ]]; then
    echo "{"
    echo "  \"network\": \"$NETWORK\","
    echo "  \"count\": $count,"
    echo "  \"base_port\": $BASE_PORT,"
    echo "  \"image\": \"$IMAGE\","
    echo "  \"nodes\": ["
    local first=1 id name gport status health leader_mark
    for ((id=1; id<=count; id++)); do
      name="$(node_name "$id")"
      gport=$((BASE_PORT + id - 1))
      status="absent"; health="-"; leader_mark="false"
      if container_exists "$name"; then
        status="$(docker inspect -f '{{.State.Status}}' "$name")"
        health="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$name" 2>/dev/null || echo none)"
        [[ "$name" == "$leader" ]] && leader_mark="true"
      fi
      [[ "$first" -eq 0 ]] && echo ","
      first=0
      printf '    {"id": %d, "name": "%s", "status": "%s", "health": "%s", "grpc_port": %d, "leader": %s}' \
        "$id" "$name" "$status" "$health" "$gport" "$leader_mark"
    done
    echo
    echo "  ]"
    echo "}"
    return
  fi

  echo
  echo "== 集群状态（${count} 节点 / 网络 $NETWORK）"
  printf '%-16s %-12s %-10s %-22s %s\n' "NAME" "STATUS" "HEALTH" "PORTS" "LEADER"
  for ((i=1; i<=count; i++)); do
    local name
    name="$(node_name "$i")"
    if ! container_exists "$name"; then
      printf '%-16s %-12s %-10s %-22s %s\n' "$name" "absent" "-" "-" "-"
      continue
    fi
    local gport=$((BASE_PORT + i - 1))
    local status health ports leader_mark
    status="$(docker inspect -f '{{.State.Status}}' "$name")"
    health="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$name" 2>/dev/null || echo none)"
    ports=":${gport}"
    leader_mark="-"
    [[ "$name" == "$leader" ]] && leader_mark="yes"
    printf '%-16s %-12s %-10s %-22s %s\n' "$name" "$status" "$health" "$ports" "$leader_mark"
  done
  echo
}

cmd_logs() {
  local node=${1:-} follow=0 lines=200
  # 解析可选项：--lines N（输出行数）、-f（跟踪）
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -f) follow=1; shift ;;
      --lines) lines="$2"; shift 2 ;;
      *) node="$1"; shift ;;
    esac
  done
  if [[ -n "$node" ]]; then
    if [[ "$follow" -eq 1 ]]; then
      docker logs -f --tail "$lines" "$(node_name "$node")"
    else
      docker logs --tail "$lines" "$(node_name "$node")" 2>&1
    fi
  else
    for c in $(docker ps -aq --filter "name=^/${CONTAINER_PREFIX}" | sort); do
      echo "===== $(docker inspect -f '{{.Name}}' "$c" | tr -d '/') ====="
      docker logs --tail "$lines" "$c" 2>&1
    done
  fi
}

# ---------- 5. mock-embed 可选依赖 ----------

embed_start() {
  if container_exists stratum-embed; then
    docker start stratum-embed >/dev/null
    log "复用 mock-embed 容器 stratum-embed"
  else
    log "启动 mock-embed（:18080）…"
    docker run -d --name stratum-embed \
      --network "$NETWORK" \
      -p "18080:8080" \
      -v "$ROOT/integration/docker/mock-embed:/app/mock-embed:ro" \
      --health-cmd "wget -q -O- http://localhost:8080/health" \
      --health-interval 5s --health-timeout 2s --health-retries 6 \
      alpine:latest /app/mock-embed >/dev/null
  fi
}

embed_stop() {
  container_exists stratum-embed && docker rm -f stratum-embed >/dev/null && log "删除 mock-embed"
}

embed_status() {
  if container_exists stratum-embed; then
    docker ps --filter name=stratum-embed --format '{{.Names}}\t{{.Status}}'
  else
    echo "mock-embed：未运行"
  fi
}

# ---------- 参数解析 ----------

usage() {
  sed -n '2,40p' "$0" | sed 's/^# \{0,1\}//'
}

# 选项可出现在命令前或命令后；其余参数（命令、节点数、节点 id 列表）顺序保留。
declare -a POS_ARGS=()
JSON_MODE=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --nodes)      DEFAULT_NODES="$2"; shift 2 ;;
    --base-port)  BASE_PORT="$2"; shift 2 ;;
    --network)    NETWORK="$2"; shift 2 ;;
    --image)      IMAGE="$2"; shift 2 ;;
    --force)      FORCE=1; shift ;;
    --with-embed) WITH_EMBED=1; shift ;;
    --json)       JSON_MODE=1; shift ;;
    # logs 子命令专属参数，原样透传
    --lines)      POS_ARGS+=("--lines" "$2"); shift 2 ;;
    -f)           POS_ARGS+=("-f"); shift ;;
    -*) die "未知参数: $1（用 help 查看用法）" ;;
    *) POS_ARGS+=("$1"); shift ;;
  esac
done

[[ "${#POS_ARGS[@]}" -lt 1 ]] && die "缺少命令（用 help 查看用法）"
CMD="${POS_ARGS[0]}"
set -- "${POS_ARGS[@]:1}"

case "$CMD" in
  build)    cmd_build ;;
  init)     cmd_init "${1:-$DEFAULT_NODES}" ;;
  up)       cmd_up "${1:-$DEFAULT_NODES}" ;;
  update)   cmd_update "${1:-$DEFAULT_NODES}" ;;
  start)    cmd_start "$@" ;;
  stop)     cmd_stop "$@" ;;
  restart)  cmd_restart "$@" ;;
  status)   cmd_status "${1:-$DEFAULT_NODES}" ;;
  logs)     cmd_logs "$@" ;;
  embed)
    case "${1:-status}" in
      start)  embed_start ;;
      stop)   embed_stop ;;
      status) embed_status ;;
      *) die "embed 子命令: start|stop|status" ;;
    esac
    ;;
  down)  cmd_down ;;
  clean) cmd_clean ;;
  help|-h|--help) usage ;;
  *) die "未知命令: $CMD（用 help 查看用法）" ;;
esac
