package bloom

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sync"

	"stratum/internal/versiondoc"
)

// versionKey identifies a single version's document bloom filter within a
// knowledge base.
type versionKey struct {
	kbID      string
	versionID int64
}

// VersionBloomStore manages the per-version document bloom filters
// (Stratum_设计文档v10.md "版本文档布隆过滤器": one filter per version,
// containing the full document ID set of that version).
//
// Lifecycle:
//   - Write path: WriteCoordinator builds the filter for the new version
//     from its full document-ID set and calls BuildAndPersist, which
//     caches it and writes it to disk.
//   - Read path: QueryService calls Get for the target version. On a
//     cache miss the filter is loaded from disk; if the on-disk copy is
//     missing or corrupt (e.g. a crash mid-write), it is rebuilt from the
//     authoritative source — the version's VersionDocList — and persisted
//     again, so a process restart never strands a version without its
//     filter.
//
// The filter is a pure accelerator: it is never the source of truth. A
// missing or stale filter degrades the read path to authoritative
// VersionDocList confirmations only, never to wrong results (Test has no
// false negatives).
type VersionBloomStore struct {
	dir           string
	expectedItems uint
	fpRate        float64
	vdl           versiondoc.VersionDocList

	mu    sync.Mutex
	cache map[versionKey]BloomFilter
}

// NewVersionBloomStore constructs a VersionBloomStore persisting filters
// under dir/bloom-version/<kbID>/<versionID>.bloom. vdl is used to rebuild
// a filter from its version's document list when no disk copy exists.
func NewVersionBloomStore(dir string, expectedItems uint, fpRate float64, vdl versiondoc.VersionDocList) *VersionBloomStore {
	return &VersionBloomStore{
		dir:           dir,
		expectedItems: expectedItems,
		fpRate:        fpRate,
		vdl:           vdl,
		cache:         make(map[versionKey]BloomFilter),
	}
}

// Get returns the document bloom filter for (kbID, versionID): from the
// in-memory cache, else from disk, else rebuilt from the version's
// VersionDocList and persisted. The returned filter must not be mutated
// by the caller.
func (s *VersionBloomStore) Get(ctx context.Context, kbID string, versionID int64) (BloomFilter, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	key := versionKey{kbID: kbID, versionID: versionID}
	if f, ok := s.cache[key]; ok {
		return f, nil
	}

	if f, err := s.loadFromDisk(kbID, versionID); err == nil {
		s.cache[key] = f
		return f, nil
	}

	// Rebuild from the authoritative source.
	docIDs, err := s.vdl.ListDocIDs(ctx, kbID, versionID)
	if err != nil {
		return nil, fmt.Errorf("bloom: VersionBloomStore.Get(%s,%d): rebuild: %w", kbID, versionID, err)
	}
	f := s.build(docIDs)
	if err := s.persist(kbID, versionID, f); err != nil {
		// A persistence failure is non-fatal: the filter is still usable
		// in memory, and the next Get will retry the disk write.
		return f, nil
	}
	s.cache[key] = f
	return f, nil
}

// BuildAndPersist builds a document bloom filter from docIDs, caches it
// and writes it to disk. Used by the write path once a version's full
// document-ID set is known. Idempotent: a repeated call for the same
// version overwrites the on-disk copy with an identical filter.
func (s *VersionBloomStore) BuildAndPersist(kbID string, versionID int64, docIDs []string) (BloomFilter, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	f := s.build(docIDs)
	if err := s.persist(kbID, versionID, f); err != nil {
		return nil, err
	}
	s.cache[versionKey{kbID: kbID, versionID: versionID}] = f
	return f, nil
}

// DeleteByKB removes kbID's on-disk version-bloom files entirely
// (dir/bloom-version/<kbID>/) and drops its filters from the cache. A
// missing directory is not an error, so re-running the knowledge-base
// delete flow after a crash is safe. Used by DeleteKnowledgeBase cleanup
// (Stratum_设计文档v10.md "删除知识库" 第 4 步).
func (s *VersionBloomStore) DeleteByKB(kbID string) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	for k := range s.cache {
		if k.kbID == kbID {
			delete(s.cache, k)
		}
	}
	if err := os.RemoveAll(filepath.Join(s.dir, "bloom-version", kbID)); err != nil {
		return fmt.Errorf("bloom: VersionBloomStore.DeleteByKB(%s): %w", kbID, err)
	}
	return nil
}

// build constructs a fresh BitsAndBloomsFilter and adds every docID.
func (s *VersionBloomStore) build(docIDs []string) *BitsAndBloomsFilter {
	f := NewBitsAndBloomsFilter(s.expectedItems, s.fpRate)
	for _, id := range docIDs {
		f.Add(id)
	}
	return f
}

// filterPath returns the on-disk path for (kbID, versionID)'s filter.
// kbID is generated by the system (a UUID), so it never contains path
// separators.
func (s *VersionBloomStore) filterPath(kbID string, versionID int64) string {
	return filepath.Join(s.dir, "bloom-version", kbID, fmt.Sprintf("%d.bloom", versionID))
}

// persist writes f's serialized form to disk (creating directories as
// needed).
func (s *VersionBloomStore) persist(kbID string, versionID int64, f BloomFilter) error {
	data, err := f.Serialize()
	if err != nil {
		return fmt.Errorf("bloom: VersionBloomStore persist(%s,%d): serialize: %w", kbID, versionID, err)
	}
	path := s.filterPath(kbID, versionID)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("bloom: VersionBloomStore persist(%s,%d): mkdir: %w", kbID, versionID, err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("bloom: VersionBloomStore persist(%s,%d): write: %w", kbID, versionID, err)
	}
	return nil
}

// loadFromDisk reads and deserializes (kbID, versionID)'s filter. Any
// error (missing file, crash-truncated write, corrupt bytes) reports a
// miss; the caller falls back to rebuilding from the version doc list.
func (s *VersionBloomStore) loadFromDisk(kbID string, versionID int64) (BloomFilter, error) {
	data, err := os.ReadFile(s.filterPath(kbID, versionID))
	if err != nil {
		return nil, err
	}
	f := NewBitsAndBloomsFilter(s.expectedItems, s.fpRate)
	if err := f.Deserialize(data); err != nil {
		return nil, err
	}
	return f, nil
}
