// admin.proto — external AdminService contract: health checks, cluster
// status, system diagnostics, and manual index maintenance operations.
//
// GetClusterStatus exists for the routing layer (cmd/stratum-router): it
// lets a router discover the current Raft leader without scanning the
// whole cluster state. External applications should prefer
// GetSystemStatus for diagnostics.
//
// See Stratum_接口设计v9.md "AdminService" for the authoritative
// specification.
//
// Reserved (not implemented): GetMetrics, GetAuditLog. Per
// Stratum_代码风格v2.md's convention of not creating empty placeholder
// files/stubs for unimplemented future work, these are documented here but
// intentionally have no corresponding RPC or message definitions yet.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: admin.proto

package stratum

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_HealthCheck_FullMethodName         = "/stratum.AdminService/HealthCheck"
	AdminService_GetSystemStatus_FullMethodName     = "/stratum.AdminService/GetSystemStatus"
	AdminService_GetClusterStatus_FullMethodName    = "/stratum.AdminService/GetClusterStatus"
	AdminService_RebuildIndex_FullMethodName        = "/stratum.AdminService/RebuildIndex"
	AdminService_WarmupVersion_FullMethodName       = "/stratum.AdminService/WarmupVersion"
	AdminService_ListFailedVersions_FullMethodName  = "/stratum.AdminService/ListFailedVersions"
	AdminService_ForceRetryVersion_FullMethodName   = "/stratum.AdminService/ForceRetryVersion"
	AdminService_ForceAbandonVersion_FullMethodName = "/stratum.AdminService/ForceAbandonVersion"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	GetSystemStatus(ctx context.Context, in *GetSystemStatusRequest, opts ...grpc.CallOption) (*GetSystemStatusResponse, error)
	GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*GetClusterStatusResponse, error)
	RebuildIndex(ctx context.Context, in *RebuildIndexRequest, opts ...grpc.CallOption) (*RebuildIndexResponse, error)
	WarmupVersion(ctx context.Context, in *WarmupVersionRequest, opts ...grpc.CallOption) (*WarmupVersionResponse, error)
	// The operator's three verbs for a version the control layer declared
	// FAILED_PERMANENT (Stratum_设计文档v13.md §10.1): see it, retry it, abandon it.
	//
	// They live here rather than on KnowledgeBaseService because the caller is an
	// operator acting on a verdict, not an application working with a version — and
	// because a deployment that never needs them can leave them unused without that
	// showing up in the application's contract.
	ListFailedVersions(ctx context.Context, in *ListFailedVersionsRequest, opts ...grpc.CallOption) (*ListFailedVersionsResponse, error)
	ForceRetryVersion(ctx context.Context, in *ForceRetryVersionRequest, opts ...grpc.CallOption) (*ForceRetryVersionResponse, error)
	ForceAbandonVersion(ctx context.Context, in *ForceAbandonVersionRequest, opts ...grpc.CallOption) (*ForceAbandonVersionResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, AdminService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetSystemStatus(ctx context.Context, in *GetSystemStatusRequest, opts ...grpc.CallOption) (*GetSystemStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSystemStatusResponse)
	err := c.cc.Invoke(ctx, AdminService_GetSystemStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*GetClusterStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterStatusResponse)
	err := c.cc.Invoke(ctx, AdminService_GetClusterStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RebuildIndex(ctx context.Context, in *RebuildIndexRequest, opts ...grpc.CallOption) (*RebuildIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebuildIndexResponse)
	err := c.cc.Invoke(ctx, AdminService_RebuildIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) WarmupVersion(ctx context.Context, in *WarmupVersionRequest, opts ...grpc.CallOption) (*WarmupVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarmupVersionResponse)
	err := c.cc.Invoke(ctx, AdminService_WarmupVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListFailedVersions(ctx context.Context, in *ListFailedVersionsRequest, opts ...grpc.CallOption) (*ListFailedVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFailedVersionsResponse)
	err := c.cc.Invoke(ctx, AdminService_ListFailedVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ForceRetryVersion(ctx context.Context, in *ForceRetryVersionRequest, opts ...grpc.CallOption) (*ForceRetryVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceRetryVersionResponse)
	err := c.cc.Invoke(ctx, AdminService_ForceRetryVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ForceAbandonVersion(ctx context.Context, in *ForceAbandonVersionRequest, opts ...grpc.CallOption) (*ForceAbandonVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceAbandonVersionResponse)
	err := c.cc.Invoke(ctx, AdminService_ForceAbandonVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
type AdminServiceServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetSystemStatus(context.Context, *GetSystemStatusRequest) (*GetSystemStatusResponse, error)
	GetClusterStatus(context.Context, *GetClusterStatusRequest) (*GetClusterStatusResponse, error)
	RebuildIndex(context.Context, *RebuildIndexRequest) (*RebuildIndexResponse, error)
	WarmupVersion(context.Context, *WarmupVersionRequest) (*WarmupVersionResponse, error)
	// The operator's three verbs for a version the control layer declared
	// FAILED_PERMANENT (Stratum_设计文档v13.md §10.1): see it, retry it, abandon it.
	//
	// They live here rather than on KnowledgeBaseService because the caller is an
	// operator acting on a verdict, not an application working with a version — and
	// because a deployment that never needs them can leave them unused without that
	// showing up in the application's contract.
	ListFailedVersions(context.Context, *ListFailedVersionsRequest) (*ListFailedVersionsResponse, error)
	ForceRetryVersion(context.Context, *ForceRetryVersionRequest) (*ForceRetryVersionResponse, error)
	ForceAbandonVersion(context.Context, *ForceAbandonVersionRequest) (*ForceAbandonVersionResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAdminServiceServer) GetSystemStatus(context.Context, *GetSystemStatusRequest) (*GetSystemStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemStatus not implemented")
}
func (UnimplementedAdminServiceServer) GetClusterStatus(context.Context, *GetClusterStatusRequest) (*GetClusterStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterStatus not implemented")
}
func (UnimplementedAdminServiceServer) RebuildIndex(context.Context, *RebuildIndexRequest) (*RebuildIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RebuildIndex not implemented")
}
func (UnimplementedAdminServiceServer) WarmupVersion(context.Context, *WarmupVersionRequest) (*WarmupVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WarmupVersion not implemented")
}
func (UnimplementedAdminServiceServer) ListFailedVersions(context.Context, *ListFailedVersionsRequest) (*ListFailedVersionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFailedVersions not implemented")
}
func (UnimplementedAdminServiceServer) ForceRetryVersion(context.Context, *ForceRetryVersionRequest) (*ForceRetryVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForceRetryVersion not implemented")
}
func (UnimplementedAdminServiceServer) ForceAbandonVersion(context.Context, *ForceAbandonVersionRequest) (*ForceAbandonVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForceAbandonVersion not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetSystemStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetSystemStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetSystemStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetSystemStatus(ctx, req.(*GetSystemStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetClusterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetClusterStatus(ctx, req.(*GetClusterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RebuildIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RebuildIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_RebuildIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RebuildIndex(ctx, req.(*RebuildIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_WarmupVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WarmupVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).WarmupVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_WarmupVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).WarmupVersion(ctx, req.(*WarmupVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListFailedVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFailedVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListFailedVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListFailedVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListFailedVersions(ctx, req.(*ListFailedVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ForceRetryVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceRetryVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ForceRetryVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ForceRetryVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ForceRetryVersion(ctx, req.(*ForceRetryVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ForceAbandonVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceAbandonVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ForceAbandonVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ForceAbandonVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ForceAbandonVersion(ctx, req.(*ForceAbandonVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stratum.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _AdminService_HealthCheck_Handler,
		},
		{
			MethodName: "GetSystemStatus",
			Handler:    _AdminService_GetSystemStatus_Handler,
		},
		{
			MethodName: "GetClusterStatus",
			Handler:    _AdminService_GetClusterStatus_Handler,
		},
		{
			MethodName: "RebuildIndex",
			Handler:    _AdminService_RebuildIndex_Handler,
		},
		{
			MethodName: "WarmupVersion",
			Handler:    _AdminService_WarmupVersion_Handler,
		},
		{
			MethodName: "ListFailedVersions",
			Handler:    _AdminService_ListFailedVersions_Handler,
		},
		{
			MethodName: "ForceRetryVersion",
			Handler:    _AdminService_ForceRetryVersion_Handler,
		},
		{
			MethodName: "ForceAbandonVersion",
			Handler:    _AdminService_ForceAbandonVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
