// internal.proto — InternalService: node-to-node control-plane traffic that is
// not part of any public API.
//
// Why it exists: Raft only lets the leader append to the log, but the facts a
// node needs to report do not always originate there. A storage replica that
// finished writing a version, or any node running its startup reconcile, has
// something to say regardless of where it landed
// (Stratum_设计文档v13.md §7.3/§7.8).
//
// Propose is the single funnel for that: the caller hands over the encoded
// command, and the receiving node runs it through Raft (it is the leader).
// The payload is metadata only — never document content.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internal.proto

package stratum

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalService_Propose_FullMethodName         = "/stratum.InternalService/Propose"
	InternalService_VersionLiveness_FullMethodName = "/stratum.InternalService/VersionLiveness"
)

// InternalServiceClient is the client API for InternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalServiceClient interface {
	// Propose runs one command through Raft on the caller's behalf. The
	// receiving node must be the leader; a node that is not answers with a
	// redirect instead of forwarding again, so a forward never chains.
	Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeResponse, error)
	// VersionLiveness answers the two facts a "was this version removed?" judgement needs,
	// from ONE view of the replicated metadata: which versions in a range are still alive,
	// and the highest id ever allocated.
	//
	// It is ONE call rather than two because the two must agree. "id <= last_allocated" is
	// what proves the view has already passed that id's allocation — the counter is
	// monotonic and every view applies in order — and only then does "and it is not alive"
	// mean REMOVED rather than "I have not got there yet". Reading the two separately could
	// combine a newer list with an older bound and call a live version gone.
	//
	// Neither fact has a lifetime, and that is what replaced the removal records this RPC
	// took the place of: a removal record is history that pruning could drop
	// (docs/known-gaps.md §B), while these are properties of the current state — nothing to
	// keep, nothing to prune, and no window in which the evidence can disappear. A storage
	// node has no state machine of its own, so this is how it judges its own leftovers.
	VersionLiveness(ctx context.Context, in *VersionLivenessRequest, opts ...grpc.CallOption) (*VersionLivenessResponse, error)
}

type internalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalServiceClient(cc grpc.ClientConnInterface) InternalServiceClient {
	return &internalServiceClient{cc}
}

func (c *internalServiceClient) Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeResponse)
	err := c.cc.Invoke(ctx, InternalService_Propose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalServiceClient) VersionLiveness(ctx context.Context, in *VersionLivenessRequest, opts ...grpc.CallOption) (*VersionLivenessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionLivenessResponse)
	err := c.cc.Invoke(ctx, InternalService_VersionLiveness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalServiceServer is the server API for InternalService service.
// All implementations must embed UnimplementedInternalServiceServer
// for forward compatibility.
type InternalServiceServer interface {
	// Propose runs one command through Raft on the caller's behalf. The
	// receiving node must be the leader; a node that is not answers with a
	// redirect instead of forwarding again, so a forward never chains.
	Propose(context.Context, *ProposeRequest) (*ProposeResponse, error)
	// VersionLiveness answers the two facts a "was this version removed?" judgement needs,
	// from ONE view of the replicated metadata: which versions in a range are still alive,
	// and the highest id ever allocated.
	//
	// It is ONE call rather than two because the two must agree. "id <= last_allocated" is
	// what proves the view has already passed that id's allocation — the counter is
	// monotonic and every view applies in order — and only then does "and it is not alive"
	// mean REMOVED rather than "I have not got there yet". Reading the two separately could
	// combine a newer list with an older bound and call a live version gone.
	//
	// Neither fact has a lifetime, and that is what replaced the removal records this RPC
	// took the place of: a removal record is history that pruning could drop
	// (docs/known-gaps.md §B), while these are properties of the current state — nothing to
	// keep, nothing to prune, and no window in which the evidence can disappear. A storage
	// node has no state machine of its own, so this is how it judges its own leftovers.
	VersionLiveness(context.Context, *VersionLivenessRequest) (*VersionLivenessResponse, error)
	mustEmbedUnimplementedInternalServiceServer()
}

// UnimplementedInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalServiceServer struct{}

func (UnimplementedInternalServiceServer) Propose(context.Context, *ProposeRequest) (*ProposeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Propose not implemented")
}
func (UnimplementedInternalServiceServer) VersionLiveness(context.Context, *VersionLivenessRequest) (*VersionLivenessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VersionLiveness not implemented")
}
func (UnimplementedInternalServiceServer) mustEmbedUnimplementedInternalServiceServer() {}
func (UnimplementedInternalServiceServer) testEmbeddedByValue()                         {}

// UnsafeInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalServiceServer will
// result in compilation errors.
type UnsafeInternalServiceServer interface {
	mustEmbedUnimplementedInternalServiceServer()
}

func RegisterInternalServiceServer(s grpc.ServiceRegistrar, srv InternalServiceServer) {
	// If the following call pancis, it indicates UnimplementedInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalService_ServiceDesc, srv)
}

func _InternalService_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_Propose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).Propose(ctx, req.(*ProposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalService_VersionLiveness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionLivenessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServiceServer).VersionLiveness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalService_VersionLiveness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServiceServer).VersionLiveness(ctx, req.(*VersionLivenessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalService_ServiceDesc is the grpc.ServiceDesc for InternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stratum.InternalService",
	HandlerType: (*InternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Propose",
			Handler:    _InternalService_Propose_Handler,
		},
		{
			MethodName: "VersionLiveness",
			Handler:    _InternalService_VersionLiveness_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal.proto",
}
