// knowledgebase.proto — external KnowledgeBaseService contract: knowledge
// base lifecycle and version management.
//
// See Stratum_接口设计v9.md "KnowledgeBaseService" for the authoritative
// specification.
//
// Reserved (not implemented): GetVersion, DiffVersions, TagVersion. Per
// Stratum_代码风格v2.md's convention of not creating empty placeholder
// files/stubs for unimplemented future work (see IVF/FLAT under vecstore),
// these are documented here but intentionally have no corresponding RPC
// or message definitions yet.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: knowledgebase.proto

package stratum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IndexStatus mirrors internal/types.IndexStatus.
type IndexStatus int32

const (
	IndexStatus_INDEX_STATUS_PENDING IndexStatus = 0 // metadata allocated, storage-layer write in progress; not queryable
	IndexStatus_INDEX_STATUS_READY   IndexStatus = 1 // index build complete; queryable
	IndexStatus_INDEX_STATUS_FAILED  IndexStatus = 2 // build failed; RebuildIndex can re-trigger
)

// Enum value maps for IndexStatus.
var (
	IndexStatus_name = map[int32]string{
		0: "INDEX_STATUS_PENDING",
		1: "INDEX_STATUS_READY",
		2: "INDEX_STATUS_FAILED",
	}
	IndexStatus_value = map[string]int32{
		"INDEX_STATUS_PENDING": 0,
		"INDEX_STATUS_READY":   1,
		"INDEX_STATUS_FAILED":  2,
	}
)

func (x IndexStatus) Enum() *IndexStatus {
	p := new(IndexStatus)
	*p = x
	return p
}

func (x IndexStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_knowledgebase_proto_enumTypes[0].Descriptor()
}

func (IndexStatus) Type() protoreflect.EnumType {
	return &file_knowledgebase_proto_enumTypes[0]
}

func (x IndexStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexStatus.Descriptor instead.
func (IndexStatus) EnumDescriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{0}
}

// IndexType mirrors KnowledgeBaseMeta.IndexType. Only HNSW has a real
// implementation today; IVF / FLAT are reserved for later iterations.
type IndexType int32

const (
	IndexType_INDEX_TYPE_HNSW IndexType = 0
	IndexType_INDEX_TYPE_IVF  IndexType = 1
	IndexType_INDEX_TYPE_FLAT IndexType = 2
)

// Enum value maps for IndexType.
var (
	IndexType_name = map[int32]string{
		0: "INDEX_TYPE_HNSW",
		1: "INDEX_TYPE_IVF",
		2: "INDEX_TYPE_FLAT",
	}
	IndexType_value = map[string]int32{
		"INDEX_TYPE_HNSW": 0,
		"INDEX_TYPE_IVF":  1,
		"INDEX_TYPE_FLAT": 2,
	}
)

func (x IndexType) Enum() *IndexType {
	p := new(IndexType)
	*p = x
	return p
}

func (x IndexType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexType) Descriptor() protoreflect.EnumDescriptor {
	return file_knowledgebase_proto_enumTypes[1].Descriptor()
}

func (IndexType) Type() protoreflect.EnumType {
	return &file_knowledgebase_proto_enumTypes[1]
}

func (x IndexType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexType.Descriptor instead.
func (IndexType) EnumDescriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{1}
}

// Similarity mirrors KnowledgeBaseMeta.Similarity.
type Similarity int32

const (
	Similarity_SIMILARITY_COSINE        Similarity = 0
	Similarity_SIMILARITY_EUCLIDEAN     Similarity = 1
	Similarity_SIMILARITY_INNER_PRODUCT Similarity = 2
)

// Enum value maps for Similarity.
var (
	Similarity_name = map[int32]string{
		0: "SIMILARITY_COSINE",
		1: "SIMILARITY_EUCLIDEAN",
		2: "SIMILARITY_INNER_PRODUCT",
	}
	Similarity_value = map[string]int32{
		"SIMILARITY_COSINE":        0,
		"SIMILARITY_EUCLIDEAN":     1,
		"SIMILARITY_INNER_PRODUCT": 2,
	}
)

func (x Similarity) Enum() *Similarity {
	p := new(Similarity)
	*p = x
	return p
}

func (x Similarity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Similarity) Descriptor() protoreflect.EnumDescriptor {
	return file_knowledgebase_proto_enumTypes[2].Descriptor()
}

func (Similarity) Type() protoreflect.EnumType {
	return &file_knowledgebase_proto_enumTypes[2]
}

func (x Similarity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Similarity.Descriptor instead.
func (Similarity) EnumDescriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{2}
}

// ChangeOp mirrors internal/types.ChangeOp.
type ChangeOp int32

const (
	ChangeOp_CHANGE_OP_ADD    ChangeOp = 0
	ChangeOp_CHANGE_OP_DELETE ChangeOp = 1
	ChangeOp_CHANGE_OP_UPDATE ChangeOp = 2
)

// Enum value maps for ChangeOp.
var (
	ChangeOp_name = map[int32]string{
		0: "CHANGE_OP_ADD",
		1: "CHANGE_OP_DELETE",
		2: "CHANGE_OP_UPDATE",
	}
	ChangeOp_value = map[string]int32{
		"CHANGE_OP_ADD":    0,
		"CHANGE_OP_DELETE": 1,
		"CHANGE_OP_UPDATE": 2,
	}
)

func (x ChangeOp) Enum() *ChangeOp {
	p := new(ChangeOp)
	*p = x
	return p
}

func (x ChangeOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeOp) Descriptor() protoreflect.EnumDescriptor {
	return file_knowledgebase_proto_enumTypes[3].Descriptor()
}

func (ChangeOp) Type() protoreflect.EnumType {
	return &file_knowledgebase_proto_enumTypes[3]
}

func (x ChangeOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeOp.Descriptor instead.
func (ChangeOp) EnumDescriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{3}
}

type EmbedConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceAddr string `protobuf:"bytes,1,opt,name=service_addr,json=serviceAddr,proto3" json:"service_addr,omitempty"`
	ModelId     string `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"` // participates in chunk ID computation: SHA-256(chunk text + model_id)
}

func (x *EmbedConfig) Reset() {
	*x = EmbedConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedConfig) ProtoMessage() {}

func (x *EmbedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedConfig.ProtoReflect.Descriptor instead.
func (*EmbedConfig) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedConfig) GetServiceAddr() string {
	if x != nil {
		return x.ServiceAddr
	}
	return ""
}

func (x *EmbedConfig) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type DocChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op      ChangeOp `protobuf:"varint,1,opt,name=op,proto3,enum=stratum.ChangeOp" json:"op,omitempty"`
	DocId   string   `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Content string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // required for ADD / UPDATE
}

func (x *DocChange) Reset() {
	*x = DocChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocChange) ProtoMessage() {}

func (x *DocChange) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocChange.ProtoReflect.Descriptor instead.
func (*DocChange) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{1}
}

func (x *DocChange) GetOp() ChangeOp {
	if x != nil {
		return x.Op
	}
	return ChangeOp_CHANGE_OP_ADD
}

func (x *DocChange) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *DocChange) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type VersionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VersionId       int64       `protobuf:"varint,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	ParentVersionId int64       `protobuf:"varint,2,opt,name=parent_version_id,json=parentVersionId,proto3" json:"parent_version_id,omitempty"`
	CreatedAt       int64       `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp, leader's local clock at apply time
	IndexStatus     IndexStatus `protobuf:"varint,4,opt,name=index_status,json=indexStatus,proto3,enum=stratum.IndexStatus" json:"index_status,omitempty"`
}

func (x *VersionInfo) Reset() {
	*x = VersionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionInfo) ProtoMessage() {}

func (x *VersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionInfo.ProtoReflect.Descriptor instead.
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{2}
}

func (x *VersionInfo) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *VersionInfo) GetParentVersionId() int64 {
	if x != nil {
		return x.ParentVersionId
	}
	return 0
}

func (x *VersionInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *VersionInfo) GetIndexStatus() IndexStatus {
	if x != nil {
		return x.IndexStatus
	}
	return IndexStatus_INDEX_STATUS_PENDING
}

type CreateKnowledgeBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ChunkWindowSize  int32        `protobuf:"varint,2,opt,name=chunk_window_size,json=chunkWindowSize,proto3" json:"chunk_window_size,omitempty"`
	ChunkOverlapSize int32        `protobuf:"varint,3,opt,name=chunk_overlap_size,json=chunkOverlapSize,proto3" json:"chunk_overlap_size,omitempty"`
	IndexType        IndexType    `protobuf:"varint,4,opt,name=index_type,json=indexType,proto3,enum=stratum.IndexType" json:"index_type,omitempty"` // optional; defaults to HNSW
	Similarity       Similarity   `protobuf:"varint,5,opt,name=similarity,proto3,enum=stratum.Similarity" json:"similarity,omitempty"`               // optional; defaults to COSINE
	EmbedConfig      *EmbedConfig `protobuf:"bytes,6,opt,name=embed_config,json=embedConfig,proto3" json:"embed_config,omitempty"`
}

func (x *CreateKnowledgeBaseRequest) Reset() {
	*x = CreateKnowledgeBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeBaseRequest) ProtoMessage() {}

func (x *CreateKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{3}
}

func (x *CreateKnowledgeBaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKnowledgeBaseRequest) GetChunkWindowSize() int32 {
	if x != nil {
		return x.ChunkWindowSize
	}
	return 0
}

func (x *CreateKnowledgeBaseRequest) GetChunkOverlapSize() int32 {
	if x != nil {
		return x.ChunkOverlapSize
	}
	return 0
}

func (x *CreateKnowledgeBaseRequest) GetIndexType() IndexType {
	if x != nil {
		return x.IndexType
	}
	return IndexType_INDEX_TYPE_HNSW
}

func (x *CreateKnowledgeBaseRequest) GetSimilarity() Similarity {
	if x != nil {
		return x.Similarity
	}
	return Similarity_SIMILARITY_COSINE
}

func (x *CreateKnowledgeBaseRequest) GetEmbedConfig() *EmbedConfig {
	if x != nil {
		return x.EmbedConfig
	}
	return nil
}

type CreateKnowledgeBaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnowledgeBaseId  string `protobuf:"bytes,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
	InitialVersionId int64  `protobuf:"varint,2,opt,name=initial_version_id,json=initialVersionId,proto3" json:"initial_version_id,omitempty"`
}

func (x *CreateKnowledgeBaseResponse) Reset() {
	*x = CreateKnowledgeBaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKnowledgeBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeBaseResponse) ProtoMessage() {}

func (x *CreateKnowledgeBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeBaseResponse.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeBaseResponse) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{4}
}

func (x *CreateKnowledgeBaseResponse) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

func (x *CreateKnowledgeBaseResponse) GetInitialVersionId() int64 {
	if x != nil {
		return x.InitialVersionId
	}
	return 0
}

type DeleteKnowledgeBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnowledgeBaseId string `protobuf:"bytes,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
}

func (x *DeleteKnowledgeBaseRequest) Reset() {
	*x = DeleteKnowledgeBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeBaseRequest) ProtoMessage() {}

func (x *DeleteKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteKnowledgeBaseRequest) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

type DeleteKnowledgeBaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // returned immediately after marking for deletion; cleanup runs asynchronously
}

func (x *DeleteKnowledgeBaseResponse) Reset() {
	*x = DeleteKnowledgeBaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKnowledgeBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeBaseResponse) ProtoMessage() {}

func (x *DeleteKnowledgeBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeBaseResponse.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeBaseResponse) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteKnowledgeBaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnowledgeBaseId string       `protobuf:"bytes,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
	ParentVersionId int64        `protobuf:"varint,2,opt,name=parent_version_id,json=parentVersionId,proto3" json:"parent_version_id,omitempty"`
	Changes         []*DocChange `protobuf:"bytes,3,rep,name=changes,proto3" json:"changes,omitempty"`
}

func (x *CreateVersionRequest) Reset() {
	*x = CreateVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionRequest) ProtoMessage() {}

func (x *CreateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionRequest.ProtoReflect.Descriptor instead.
func (*CreateVersionRequest) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{7}
}

func (x *CreateVersionRequest) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

func (x *CreateVersionRequest) GetParentVersionId() int64 {
	if x != nil {
		return x.ParentVersionId
	}
	return 0
}

func (x *CreateVersionRequest) GetChanges() []*DocChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type CreateVersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VersionId int64 `protobuf:"varint,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"` // newly created version; PENDING, index building asynchronously
}

func (x *CreateVersionResponse) Reset() {
	*x = CreateVersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionResponse) ProtoMessage() {}

func (x *CreateVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionResponse.ProtoReflect.Descriptor instead.
func (*CreateVersionResponse) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{8}
}

func (x *CreateVersionResponse) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

type ListVersionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnowledgeBaseId string `protobuf:"bytes,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{9}
}

func (x *ListVersionsRequest) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

type ListVersionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Versions []*VersionInfo `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{10}
}

func (x *ListVersionsResponse) GetVersions() []*VersionInfo {
	if x != nil {
		return x.Versions
	}
	return nil
}

type RollbackVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnowledgeBaseId string `protobuf:"bytes,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
	TargetVersionId int64  `protobuf:"varint,2,opt,name=target_version_id,json=targetVersionId,proto3" json:"target_version_id,omitempty"`
}

func (x *RollbackVersionRequest) Reset() {
	*x = RollbackVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollbackVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackVersionRequest) ProtoMessage() {}

func (x *RollbackVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackVersionRequest.ProtoReflect.Descriptor instead.
func (*RollbackVersionRequest) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{11}
}

func (x *RollbackVersionRequest) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

func (x *RollbackVersionRequest) GetTargetVersionId() int64 {
	if x != nil {
		return x.TargetVersionId
	}
	return 0
}

type RollbackVersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RollbackVersionResponse) Reset() {
	*x = RollbackVersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollbackVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackVersionResponse) ProtoMessage() {}

func (x *RollbackVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackVersionResponse.ProtoReflect.Descriptor instead.
func (*RollbackVersionResponse) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{12}
}

func (x *RollbackVersionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_knowledgebase_proto protoreflect.FileDescriptor

var file_knowledgebase_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x22, 0x4b,
	0x0a, 0x0b, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x21, 0x0a,
	0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72,
	0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x5f, 0x0a, 0x09, 0x44,
	0x6f, 0x63, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x64,
	0x6f, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x6f, 0x63,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xb0, 0x01, 0x0a,
	0x0b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x37, 0x0a, 0x0c, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x0b, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0xab, 0x02, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x77, 0x69, 0x6e, 0x64,
	0x6f, 0x77, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x2c,
	0x0a, 0x12, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x70, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x63, 0x68, 0x75, 0x6e,
	0x6b, 0x4f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x70, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x31, 0x0a, 0x0a,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x33, 0x0a, 0x0a, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x53, 0x69,
	0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61,
	0x72, 0x69, 0x74, 0x79, 0x12, 0x37, 0x0a, 0x0c, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x5f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x75, 0x6d, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x52, 0x0b, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x77, 0x0a,
	0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x11,
	0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64,
	0x22, 0x37, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x9c, 0x01, 0x0a, 0x14, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x5f,
	0x62, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6b,
	0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x2a,
	0x0a, 0x11, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x44, 0x6f, 0x63, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52,
	0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x22, 0x36, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x22, 0x41, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x6b, 0x6e, 0x6f, 0x77, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73,
	0x65, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x70, 0x0a,
	0x16, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x6b, 0x6e, 0x6f, 0x77, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73,
	0x65, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22,
	0x33, 0x0a, 0x17, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x2a, 0x58, 0x0a, 0x0b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x14, 0x49, 0x4e, 0x44, 0x45, 0x58, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x16, 0x0a,
	0x12, 0x49, 0x4e, 0x44, 0x45, 0x58, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x45,
	0x41, 0x44, 0x59, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x49, 0x4e, 0x44, 0x45, 0x58, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x49,
	0x0a, 0x09, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x49,
	0x4e, 0x44, 0x45, 0x58, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x48, 0x4e, 0x53, 0x57, 0x10, 0x00,
	0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x44, 0x45, 0x58, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49,
	0x56, 0x46, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x4e, 0x44, 0x45, 0x58, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x46, 0x4c, 0x41, 0x54, 0x10, 0x02, 0x2a, 0x5b, 0x0a, 0x0a, 0x53, 0x69, 0x6d,
	0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x49, 0x4d, 0x49, 0x4c,
	0x41, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x43, 0x4f, 0x53, 0x49, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x18,
	0x0a, 0x14, 0x53, 0x49, 0x4d, 0x49, 0x4c, 0x41, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x45, 0x55, 0x43,
	0x4c, 0x49, 0x44, 0x45, 0x41, 0x4e, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x53, 0x49, 0x4d, 0x49,
	0x4c, 0x41, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x49, 0x4e, 0x4e, 0x45, 0x52, 0x5f, 0x50, 0x52, 0x4f,
	0x44, 0x55, 0x43, 0x54, 0x10, 0x02, 0x2a, 0x49, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x4f, 0x70, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x4f, 0x50, 0x5f,
	0x41, 0x44, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f,
	0x4f, 0x50, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x43,
	0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x4f, 0x50, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10,
	0x02, 0x32, 0xcd, 0x03, 0x0a, 0x14, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42,
	0x61, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73,
	0x65, 0x12, 0x23, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x13,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42,
	0x61, 0x73, 0x65, 0x12, 0x23, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x75, 0x6d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e,
	0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1d, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b,
	0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c,
	0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x0f, 0x52,
	0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f,
	0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x1b, 0x5a, 0x19, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_knowledgebase_proto_rawDescOnce sync.Once
	file_knowledgebase_proto_rawDescData = file_knowledgebase_proto_rawDesc
)

func file_knowledgebase_proto_rawDescGZIP() []byte {
	file_knowledgebase_proto_rawDescOnce.Do(func() {
		file_knowledgebase_proto_rawDescData = protoimpl.X.CompressGZIP(file_knowledgebase_proto_rawDescData)
	})
	return file_knowledgebase_proto_rawDescData
}

var file_knowledgebase_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_knowledgebase_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_knowledgebase_proto_goTypes = []any{
	(IndexStatus)(0),                    // 0: stratum.IndexStatus
	(IndexType)(0),                      // 1: stratum.IndexType
	(Similarity)(0),                     // 2: stratum.Similarity
	(ChangeOp)(0),                       // 3: stratum.ChangeOp
	(*EmbedConfig)(nil),                 // 4: stratum.EmbedConfig
	(*DocChange)(nil),                   // 5: stratum.DocChange
	(*VersionInfo)(nil),                 // 6: stratum.VersionInfo
	(*CreateKnowledgeBaseRequest)(nil),  // 7: stratum.CreateKnowledgeBaseRequest
	(*CreateKnowledgeBaseResponse)(nil), // 8: stratum.CreateKnowledgeBaseResponse
	(*DeleteKnowledgeBaseRequest)(nil),  // 9: stratum.DeleteKnowledgeBaseRequest
	(*DeleteKnowledgeBaseResponse)(nil), // 10: stratum.DeleteKnowledgeBaseResponse
	(*CreateVersionRequest)(nil),        // 11: stratum.CreateVersionRequest
	(*CreateVersionResponse)(nil),       // 12: stratum.CreateVersionResponse
	(*ListVersionsRequest)(nil),         // 13: stratum.ListVersionsRequest
	(*ListVersionsResponse)(nil),        // 14: stratum.ListVersionsResponse
	(*RollbackVersionRequest)(nil),      // 15: stratum.RollbackVersionRequest
	(*RollbackVersionResponse)(nil),     // 16: stratum.RollbackVersionResponse
}
var file_knowledgebase_proto_depIdxs = []int32{
	3,  // 0: stratum.DocChange.op:type_name -> stratum.ChangeOp
	0,  // 1: stratum.VersionInfo.index_status:type_name -> stratum.IndexStatus
	1,  // 2: stratum.CreateKnowledgeBaseRequest.index_type:type_name -> stratum.IndexType
	2,  // 3: stratum.CreateKnowledgeBaseRequest.similarity:type_name -> stratum.Similarity
	4,  // 4: stratum.CreateKnowledgeBaseRequest.embed_config:type_name -> stratum.EmbedConfig
	5,  // 5: stratum.CreateVersionRequest.changes:type_name -> stratum.DocChange
	6,  // 6: stratum.ListVersionsResponse.versions:type_name -> stratum.VersionInfo
	7,  // 7: stratum.KnowledgeBaseService.CreateKnowledgeBase:input_type -> stratum.CreateKnowledgeBaseRequest
	9,  // 8: stratum.KnowledgeBaseService.DeleteKnowledgeBase:input_type -> stratum.DeleteKnowledgeBaseRequest
	11, // 9: stratum.KnowledgeBaseService.CreateVersion:input_type -> stratum.CreateVersionRequest
	13, // 10: stratum.KnowledgeBaseService.ListVersions:input_type -> stratum.ListVersionsRequest
	15, // 11: stratum.KnowledgeBaseService.RollbackVersion:input_type -> stratum.RollbackVersionRequest
	8,  // 12: stratum.KnowledgeBaseService.CreateKnowledgeBase:output_type -> stratum.CreateKnowledgeBaseResponse
	10, // 13: stratum.KnowledgeBaseService.DeleteKnowledgeBase:output_type -> stratum.DeleteKnowledgeBaseResponse
	12, // 14: stratum.KnowledgeBaseService.CreateVersion:output_type -> stratum.CreateVersionResponse
	14, // 15: stratum.KnowledgeBaseService.ListVersions:output_type -> stratum.ListVersionsResponse
	16, // 16: stratum.KnowledgeBaseService.RollbackVersion:output_type -> stratum.RollbackVersionResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_knowledgebase_proto_init() }
func file_knowledgebase_proto_init() {
	if File_knowledgebase_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_knowledgebase_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EmbedConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DocChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*VersionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateKnowledgeBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreateKnowledgeBaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteKnowledgeBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteKnowledgeBaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CreateVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CreateVersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListVersionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ListVersionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*RollbackVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*RollbackVersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_knowledgebase_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_knowledgebase_proto_goTypes,
		DependencyIndexes: file_knowledgebase_proto_depIdxs,
		EnumInfos:         file_knowledgebase_proto_enumTypes,
		MessageInfos:      file_knowledgebase_proto_msgTypes,
	}.Build()
	File_knowledgebase_proto = out.File
	file_knowledgebase_proto_rawDesc = nil
	file_knowledgebase_proto_goTypes = nil
	file_knowledgebase_proto_depIdxs = nil
}
