// knowledgebase.proto — external KnowledgeBaseService contract: knowledge
// base lifecycle and version management.
//
// See Stratum_接口设计v9.md "KnowledgeBaseService" for the authoritative
// specification.
//
// Reserved (not implemented): GetVersion, DiffVersions, TagVersion. Per
// Stratum_代码风格v2.md's convention of not creating empty placeholder
// files/stubs for unimplemented future work (see IVF/FLAT under vecstore),
// these are documented here but intentionally have no corresponding RPC
// or message definitions yet.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: knowledgebase.proto

package stratum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IndexStatus mirrors internal/types.IndexStatus.
type IndexStatus int32

const (
	IndexStatus_INDEX_STATUS_PENDING IndexStatus = 0 // metadata allocated, storage-layer write in progress; not queryable
	IndexStatus_INDEX_STATUS_READY   IndexStatus = 1 // index build complete; queryable
	IndexStatus_INDEX_STATUS_FAILED  IndexStatus = 2 // build failed; RebuildIndex can re-trigger
)

// Enum value maps for IndexStatus.
var (
	IndexStatus_name = map[int32]string{
		0: "INDEX_STATUS_PENDING",
		1: "INDEX_STATUS_READY",
		2: "INDEX_STATUS_FAILED",
	}
	IndexStatus_value = map[string]int32{
		"INDEX_STATUS_PENDING": 0,
		"INDEX_STATUS_READY":   1,
		"INDEX_STATUS_FAILED":  2,
	}
)

func (x IndexStatus) Enum() *IndexStatus {
	p := new(IndexStatus)
	*p = x
	return p
}

func (x IndexStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_knowledgebase_proto_enumTypes[0].Descriptor()
}

func (IndexStatus) Type() protoreflect.EnumType {
	return &file_knowledgebase_proto_enumTypes[0]
}

func (x IndexStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexStatus.Descriptor instead.
func (IndexStatus) EnumDescriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{0}
}

// IndexType mirrors KnowledgeBaseMeta.IndexType. Only HNSW has a real
// implementation today; IVF / FLAT are reserved for later iterations.
type IndexType int32

const (
	IndexType_INDEX_TYPE_HNSW IndexType = 0
	IndexType_INDEX_TYPE_IVF  IndexType = 1
	IndexType_INDEX_TYPE_FLAT IndexType = 2
)

// Enum value maps for IndexType.
var (
	IndexType_name = map[int32]string{
		0: "INDEX_TYPE_HNSW",
		1: "INDEX_TYPE_IVF",
		2: "INDEX_TYPE_FLAT",
	}
	IndexType_value = map[string]int32{
		"INDEX_TYPE_HNSW": 0,
		"INDEX_TYPE_IVF":  1,
		"INDEX_TYPE_FLAT": 2,
	}
)

func (x IndexType) Enum() *IndexType {
	p := new(IndexType)
	*p = x
	return p
}

func (x IndexType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexType) Descriptor() protoreflect.EnumDescriptor {
	return file_knowledgebase_proto_enumTypes[1].Descriptor()
}

func (IndexType) Type() protoreflect.EnumType {
	return &file_knowledgebase_proto_enumTypes[1]
}

func (x IndexType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexType.Descriptor instead.
func (IndexType) EnumDescriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{1}
}

// Similarity mirrors KnowledgeBaseMeta.Similarity.
type Similarity int32

const (
	Similarity_SIMILARITY_COSINE        Similarity = 0
	Similarity_SIMILARITY_EUCLIDEAN     Similarity = 1
	Similarity_SIMILARITY_INNER_PRODUCT Similarity = 2
)

// Enum value maps for Similarity.
var (
	Similarity_name = map[int32]string{
		0: "SIMILARITY_COSINE",
		1: "SIMILARITY_EUCLIDEAN",
		2: "SIMILARITY_INNER_PRODUCT",
	}
	Similarity_value = map[string]int32{
		"SIMILARITY_COSINE":        0,
		"SIMILARITY_EUCLIDEAN":     1,
		"SIMILARITY_INNER_PRODUCT": 2,
	}
)

func (x Similarity) Enum() *Similarity {
	p := new(Similarity)
	*p = x
	return p
}

func (x Similarity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Similarity) Descriptor() protoreflect.EnumDescriptor {
	return file_knowledgebase_proto_enumTypes[2].Descriptor()
}

func (Similarity) Type() protoreflect.EnumType {
	return &file_knowledgebase_proto_enumTypes[2]
}

func (x Similarity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Similarity.Descriptor instead.
func (Similarity) EnumDescriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{2}
}

// QuantizerType mirrors the vecstore-side QuantizerTypeProto
// (Stratum_设计文档v12.md 2.4): how the in-memory index stores vector
// payloads. QUANTIZER_OFF keeps full-precision HNSW (single-stage exact
// search); the others build quantized coarse retrievers whose results are
// re-ranked against full-precision vectors on disk.
type QuantizerType int32

const (
	QuantizerType_QUANTIZER_OFF     QuantizerType = 0
	QuantizerType_QUANTIZER_SQ8     QuantizerType = 1
	QuantizerType_QUANTIZER_SQ_BF16 QuantizerType = 2
	QuantizerType_QUANTIZER_SQ_FP16 QuantizerType = 3
	QuantizerType_QUANTIZER_PQ      QuantizerType = 4
)

// Enum value maps for QuantizerType.
var (
	QuantizerType_name = map[int32]string{
		0: "QUANTIZER_OFF",
		1: "QUANTIZER_SQ8",
		2: "QUANTIZER_SQ_BF16",
		3: "QUANTIZER_SQ_FP16",
		4: "QUANTIZER_PQ",
	}
	QuantizerType_value = map[string]int32{
		"QUANTIZER_OFF":     0,
		"QUANTIZER_SQ8":     1,
		"QUANTIZER_SQ_BF16": 2,
		"QUANTIZER_SQ_FP16": 3,
		"QUANTIZER_PQ":      4,
	}
)

func (x QuantizerType) Enum() *QuantizerType {
	p := new(QuantizerType)
	*p = x
	return p
}

func (x QuantizerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuantizerType) Descriptor() protoreflect.EnumDescriptor {
	return file_knowledgebase_proto_enumTypes[3].Descriptor()
}

func (QuantizerType) Type() protoreflect.EnumType {
	return &file_knowledgebase_proto_enumTypes[3]
}

func (x QuantizerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuantizerType.Descriptor instead.
func (QuantizerType) EnumDescriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{3}
}

// KBStatus mirrors internal/types.KBStatus.
type KBStatus int32

const (
	KBStatus_KB_STATUS_ACTIVE        KBStatus = 0
	KBStatus_KB_STATUS_DELETING      KBStatus = 1
	KBStatus_KB_STATUS_DELETE_FAILED KBStatus = 2
)

// Enum value maps for KBStatus.
var (
	KBStatus_name = map[int32]string{
		0: "KB_STATUS_ACTIVE",
		1: "KB_STATUS_DELETING",
		2: "KB_STATUS_DELETE_FAILED",
	}
	KBStatus_value = map[string]int32{
		"KB_STATUS_ACTIVE":        0,
		"KB_STATUS_DELETING":      1,
		"KB_STATUS_DELETE_FAILED": 2,
	}
)

func (x KBStatus) Enum() *KBStatus {
	p := new(KBStatus)
	*p = x
	return p
}

func (x KBStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KBStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_knowledgebase_proto_enumTypes[4].Descriptor()
}

func (KBStatus) Type() protoreflect.EnumType {
	return &file_knowledgebase_proto_enumTypes[4]
}

func (x KBStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KBStatus.Descriptor instead.
func (KBStatus) EnumDescriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{4}
}

// ChangeOp mirrors internal/types.ChangeOp.
type ChangeOp int32

const (
	ChangeOp_CHANGE_OP_ADD    ChangeOp = 0
	ChangeOp_CHANGE_OP_DELETE ChangeOp = 1
	ChangeOp_CHANGE_OP_UPDATE ChangeOp = 2
)

// Enum value maps for ChangeOp.
var (
	ChangeOp_name = map[int32]string{
		0: "CHANGE_OP_ADD",
		1: "CHANGE_OP_DELETE",
		2: "CHANGE_OP_UPDATE",
	}
	ChangeOp_value = map[string]int32{
		"CHANGE_OP_ADD":    0,
		"CHANGE_OP_DELETE": 1,
		"CHANGE_OP_UPDATE": 2,
	}
)

func (x ChangeOp) Enum() *ChangeOp {
	p := new(ChangeOp)
	*p = x
	return p
}

func (x ChangeOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeOp) Descriptor() protoreflect.EnumDescriptor {
	return file_knowledgebase_proto_enumTypes[5].Descriptor()
}

func (ChangeOp) Type() protoreflect.EnumType {
	return &file_knowledgebase_proto_enumTypes[5]
}

func (x ChangeOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeOp.Descriptor instead.
func (ChangeOp) EnumDescriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{5}
}

type EmbedConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceAddr string `protobuf:"bytes,1,opt,name=service_addr,json=serviceAddr,proto3" json:"service_addr,omitempty"`
	ModelId     string `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"` // participates in chunk ID computation: SHA-256(chunk text + model_id)
}

func (x *EmbedConfig) Reset() {
	*x = EmbedConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedConfig) ProtoMessage() {}

func (x *EmbedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedConfig.ProtoReflect.Descriptor instead.
func (*EmbedConfig) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedConfig) GetServiceAddr() string {
	if x != nil {
		return x.ServiceAddr
	}
	return ""
}

func (x *EmbedConfig) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type DocChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op      ChangeOp `protobuf:"varint,1,opt,name=op,proto3,enum=stratum.ChangeOp" json:"op,omitempty"`
	DocId   string   `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Content string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // required for ADD / UPDATE
}

func (x *DocChange) Reset() {
	*x = DocChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocChange) ProtoMessage() {}

func (x *DocChange) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocChange.ProtoReflect.Descriptor instead.
func (*DocChange) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{1}
}

func (x *DocChange) GetOp() ChangeOp {
	if x != nil {
		return x.Op
	}
	return ChangeOp_CHANGE_OP_ADD
}

func (x *DocChange) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *DocChange) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type VersionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VersionId       int64       `protobuf:"varint,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	ParentVersionId int64       `protobuf:"varint,2,opt,name=parent_version_id,json=parentVersionId,proto3" json:"parent_version_id,omitempty"`
	CreatedAt       int64       `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp, leader's local clock at apply time
	IndexStatus     IndexStatus `protobuf:"varint,4,opt,name=index_status,json=indexStatus,proto3,enum=stratum.IndexStatus" json:"index_status,omitempty"`
	Deleting        bool        `protobuf:"varint,5,opt,name=deleting,proto3" json:"deleting,omitempty"` // true while an asynchronous DeleteVersion cleanup is in progress
}

func (x *VersionInfo) Reset() {
	*x = VersionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionInfo) ProtoMessage() {}

func (x *VersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionInfo.ProtoReflect.Descriptor instead.
func (*VersionInfo) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{2}
}

func (x *VersionInfo) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *VersionInfo) GetParentVersionId() int64 {
	if x != nil {
		return x.ParentVersionId
	}
	return 0
}

func (x *VersionInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *VersionInfo) GetIndexStatus() IndexStatus {
	if x != nil {
		return x.IndexStatus
	}
	return IndexStatus_INDEX_STATUS_PENDING
}

func (x *VersionInfo) GetDeleting() bool {
	if x != nil {
		return x.Deleting
	}
	return false
}

// KnowledgeBaseInfo is the console-facing metadata of a knowledge base,
// returned by ListKnowledgeBases / GetKnowledgeBase.
type KnowledgeBaseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnowledgeBaseId  string        `protobuf:"bytes,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
	Name             string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ChunkWindowSize  int32         `protobuf:"varint,3,opt,name=chunk_window_size,json=chunkWindowSize,proto3" json:"chunk_window_size,omitempty"`
	ChunkOverlapSize int32         `protobuf:"varint,4,opt,name=chunk_overlap_size,json=chunkOverlapSize,proto3" json:"chunk_overlap_size,omitempty"`
	IndexType        IndexType     `protobuf:"varint,5,opt,name=index_type,json=indexType,proto3,enum=stratum.IndexType" json:"index_type,omitempty"`
	Similarity       Similarity    `protobuf:"varint,6,opt,name=similarity,proto3,enum=stratum.Similarity" json:"similarity,omitempty"`
	EmbedConfig      *EmbedConfig  `protobuf:"bytes,7,opt,name=embed_config,json=embedConfig,proto3" json:"embed_config,omitempty"`
	ActiveVersionId  int64         `protobuf:"varint,8,opt,name=active_version_id,json=activeVersionId,proto3" json:"active_version_id,omitempty"`
	Status           KBStatus      `protobuf:"varint,9,opt,name=status,proto3,enum=stratum.KBStatus" json:"status,omitempty"`
	Quantizer        QuantizerType `protobuf:"varint,10,opt,name=quantizer,proto3,enum=stratum.QuantizerType" json:"quantizer,omitempty"` // immutable after creation; default OFF
	PqM              int32         `protobuf:"varint,11,opt,name=pq_m,json=pqM,proto3" json:"pq_m,omitempty"`                             // PQ only; default 96
	PqNbits          int32         `protobuf:"varint,12,opt,name=pq_nbits,json=pqNbits,proto3" json:"pq_nbits,omitempty"`                 // PQ only; default 8
}

func (x *KnowledgeBaseInfo) Reset() {
	*x = KnowledgeBaseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KnowledgeBaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeBaseInfo) ProtoMessage() {}

func (x *KnowledgeBaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeBaseInfo.ProtoReflect.Descriptor instead.
func (*KnowledgeBaseInfo) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{3}
}

func (x *KnowledgeBaseInfo) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

func (x *KnowledgeBaseInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KnowledgeBaseInfo) GetChunkWindowSize() int32 {
	if x != nil {
		return x.ChunkWindowSize
	}
	return 0
}

func (x *KnowledgeBaseInfo) GetChunkOverlapSize() int32 {
	if x != nil {
		return x.ChunkOverlapSize
	}
	return 0
}

func (x *KnowledgeBaseInfo) GetIndexType() IndexType {
	if x != nil {
		return x.IndexType
	}
	return IndexType_INDEX_TYPE_HNSW
}

func (x *KnowledgeBaseInfo) GetSimilarity() Similarity {
	if x != nil {
		return x.Similarity
	}
	return Similarity_SIMILARITY_COSINE
}

func (x *KnowledgeBaseInfo) GetEmbedConfig() *EmbedConfig {
	if x != nil {
		return x.EmbedConfig
	}
	return nil
}

func (x *KnowledgeBaseInfo) GetActiveVersionId() int64 {
	if x != nil {
		return x.ActiveVersionId
	}
	return 0
}

func (x *KnowledgeBaseInfo) GetStatus() KBStatus {
	if x != nil {
		return x.Status
	}
	return KBStatus_KB_STATUS_ACTIVE
}

func (x *KnowledgeBaseInfo) GetQuantizer() QuantizerType {
	if x != nil {
		return x.Quantizer
	}
	return QuantizerType_QUANTIZER_OFF
}

func (x *KnowledgeBaseInfo) GetPqM() int32 {
	if x != nil {
		return x.PqM
	}
	return 0
}

func (x *KnowledgeBaseInfo) GetPqNbits() int32 {
	if x != nil {
		return x.PqNbits
	}
	return 0
}

type CreateKnowledgeBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ChunkWindowSize  int32         `protobuf:"varint,2,opt,name=chunk_window_size,json=chunkWindowSize,proto3" json:"chunk_window_size,omitempty"`
	ChunkOverlapSize int32         `protobuf:"varint,3,opt,name=chunk_overlap_size,json=chunkOverlapSize,proto3" json:"chunk_overlap_size,omitempty"`
	IndexType        IndexType     `protobuf:"varint,4,opt,name=index_type,json=indexType,proto3,enum=stratum.IndexType" json:"index_type,omitempty"` // optional; defaults to HNSW
	Similarity       Similarity    `protobuf:"varint,5,opt,name=similarity,proto3,enum=stratum.Similarity" json:"similarity,omitempty"`               // optional; defaults to COSINE
	EmbedConfig      *EmbedConfig  `protobuf:"bytes,6,opt,name=embed_config,json=embedConfig,proto3" json:"embed_config,omitempty"`
	Quantizer        QuantizerType `protobuf:"varint,7,opt,name=quantizer,proto3,enum=stratum.QuantizerType" json:"quantizer,omitempty"` // optional; defaults to QUANTIZER_OFF
	PqM              int32         `protobuf:"varint,8,opt,name=pq_m,json=pqM,proto3" json:"pq_m,omitempty"`                             // PQ only; 0 = default 96
	PqNbits          int32         `protobuf:"varint,9,opt,name=pq_nbits,json=pqNbits,proto3" json:"pq_nbits,omitempty"`                 // PQ only; 0 = default 8
}

func (x *CreateKnowledgeBaseRequest) Reset() {
	*x = CreateKnowledgeBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeBaseRequest) ProtoMessage() {}

func (x *CreateKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{4}
}

func (x *CreateKnowledgeBaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKnowledgeBaseRequest) GetChunkWindowSize() int32 {
	if x != nil {
		return x.ChunkWindowSize
	}
	return 0
}

func (x *CreateKnowledgeBaseRequest) GetChunkOverlapSize() int32 {
	if x != nil {
		return x.ChunkOverlapSize
	}
	return 0
}

func (x *CreateKnowledgeBaseRequest) GetIndexType() IndexType {
	if x != nil {
		return x.IndexType
	}
	return IndexType_INDEX_TYPE_HNSW
}

func (x *CreateKnowledgeBaseRequest) GetSimilarity() Similarity {
	if x != nil {
		return x.Similarity
	}
	return Similarity_SIMILARITY_COSINE
}

func (x *CreateKnowledgeBaseRequest) GetEmbedConfig() *EmbedConfig {
	if x != nil {
		return x.EmbedConfig
	}
	return nil
}

func (x *CreateKnowledgeBaseRequest) GetQuantizer() QuantizerType {
	if x != nil {
		return x.Quantizer
	}
	return QuantizerType_QUANTIZER_OFF
}

func (x *CreateKnowledgeBaseRequest) GetPqM() int32 {
	if x != nil {
		return x.PqM
	}
	return 0
}

func (x *CreateKnowledgeBaseRequest) GetPqNbits() int32 {
	if x != nil {
		return x.PqNbits
	}
	return 0
}

type CreateKnowledgeBaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnowledgeBaseId  string `protobuf:"bytes,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
	InitialVersionId int64  `protobuf:"varint,2,opt,name=initial_version_id,json=initialVersionId,proto3" json:"initial_version_id,omitempty"`
}

func (x *CreateKnowledgeBaseResponse) Reset() {
	*x = CreateKnowledgeBaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKnowledgeBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeBaseResponse) ProtoMessage() {}

func (x *CreateKnowledgeBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeBaseResponse.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeBaseResponse) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{5}
}

func (x *CreateKnowledgeBaseResponse) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

func (x *CreateKnowledgeBaseResponse) GetInitialVersionId() int64 {
	if x != nil {
		return x.InitialVersionId
	}
	return 0
}

type DeleteKnowledgeBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnowledgeBaseId string `protobuf:"bytes,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
}

func (x *DeleteKnowledgeBaseRequest) Reset() {
	*x = DeleteKnowledgeBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeBaseRequest) ProtoMessage() {}

func (x *DeleteKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteKnowledgeBaseRequest) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

type DeleteKnowledgeBaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // returned immediately after marking for deletion; cleanup runs asynchronously
}

func (x *DeleteKnowledgeBaseResponse) Reset() {
	*x = DeleteKnowledgeBaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKnowledgeBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeBaseResponse) ProtoMessage() {}

func (x *DeleteKnowledgeBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeBaseResponse.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeBaseResponse) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteKnowledgeBaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnowledgeBaseId string       `protobuf:"bytes,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
	ParentVersionId int64        `protobuf:"varint,2,opt,name=parent_version_id,json=parentVersionId,proto3" json:"parent_version_id,omitempty"`
	Changes         []*DocChange `protobuf:"bytes,3,rep,name=changes,proto3" json:"changes,omitempty"`
}

func (x *CreateVersionRequest) Reset() {
	*x = CreateVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionRequest) ProtoMessage() {}

func (x *CreateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionRequest.ProtoReflect.Descriptor instead.
func (*CreateVersionRequest) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{8}
}

func (x *CreateVersionRequest) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

func (x *CreateVersionRequest) GetParentVersionId() int64 {
	if x != nil {
		return x.ParentVersionId
	}
	return 0
}

func (x *CreateVersionRequest) GetChanges() []*DocChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type CreateVersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VersionId int64 `protobuf:"varint,1,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"` // newly created version; PENDING, index building asynchronously
}

func (x *CreateVersionResponse) Reset() {
	*x = CreateVersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionResponse) ProtoMessage() {}

func (x *CreateVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionResponse.ProtoReflect.Descriptor instead.
func (*CreateVersionResponse) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{9}
}

func (x *CreateVersionResponse) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

type ListVersionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnowledgeBaseId string `protobuf:"bytes,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
}

func (x *ListVersionsRequest) Reset() {
	*x = ListVersionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsRequest) ProtoMessage() {}

func (x *ListVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListVersionsRequest) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{10}
}

func (x *ListVersionsRequest) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

type ListVersionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Versions []*VersionInfo `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
}

func (x *ListVersionsResponse) Reset() {
	*x = ListVersionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVersionsResponse) ProtoMessage() {}

func (x *ListVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListVersionsResponse) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{11}
}

func (x *ListVersionsResponse) GetVersions() []*VersionInfo {
	if x != nil {
		return x.Versions
	}
	return nil
}

type RollbackVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnowledgeBaseId string `protobuf:"bytes,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
	TargetVersionId int64  `protobuf:"varint,2,opt,name=target_version_id,json=targetVersionId,proto3" json:"target_version_id,omitempty"`
}

func (x *RollbackVersionRequest) Reset() {
	*x = RollbackVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollbackVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackVersionRequest) ProtoMessage() {}

func (x *RollbackVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackVersionRequest.ProtoReflect.Descriptor instead.
func (*RollbackVersionRequest) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{12}
}

func (x *RollbackVersionRequest) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

func (x *RollbackVersionRequest) GetTargetVersionId() int64 {
	if x != nil {
		return x.TargetVersionId
	}
	return 0
}

type RollbackVersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RollbackVersionResponse) Reset() {
	*x = RollbackVersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollbackVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackVersionResponse) ProtoMessage() {}

func (x *RollbackVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackVersionResponse.ProtoReflect.Descriptor instead.
func (*RollbackVersionResponse) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{13}
}

func (x *RollbackVersionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnowledgeBaseId string `protobuf:"bytes,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
	VersionId       int64  `protobuf:"varint,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
}

func (x *DeleteVersionRequest) Reset() {
	*x = DeleteVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVersionRequest) ProtoMessage() {}

func (x *DeleteVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVersionRequest.ProtoReflect.Descriptor instead.
func (*DeleteVersionRequest) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteVersionRequest) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

func (x *DeleteVersionRequest) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

type DeleteVersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // returned immediately after marking the version (and its descendants) for deletion; cleanup runs asynchronously
}

func (x *DeleteVersionResponse) Reset() {
	*x = DeleteVersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVersionResponse) ProtoMessage() {}

func (x *DeleteVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVersionResponse.ProtoReflect.Descriptor instead.
func (*DeleteVersionResponse) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteVersionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListKnowledgeBasesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListKnowledgeBasesRequest) Reset() {
	*x = ListKnowledgeBasesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKnowledgeBasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeBasesRequest) ProtoMessage() {}

func (x *ListKnowledgeBasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeBasesRequest.ProtoReflect.Descriptor instead.
func (*ListKnowledgeBasesRequest) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{16}
}

type ListKnowledgeBasesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnowledgeBases []*KnowledgeBaseInfo `protobuf:"bytes,1,rep,name=knowledge_bases,json=knowledgeBases,proto3" json:"knowledge_bases,omitempty"`
}

func (x *ListKnowledgeBasesResponse) Reset() {
	*x = ListKnowledgeBasesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKnowledgeBasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeBasesResponse) ProtoMessage() {}

func (x *ListKnowledgeBasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeBasesResponse.ProtoReflect.Descriptor instead.
func (*ListKnowledgeBasesResponse) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{17}
}

func (x *ListKnowledgeBasesResponse) GetKnowledgeBases() []*KnowledgeBaseInfo {
	if x != nil {
		return x.KnowledgeBases
	}
	return nil
}

type GetKnowledgeBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnowledgeBaseId string `protobuf:"bytes,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
}

func (x *GetKnowledgeBaseRequest) Reset() {
	*x = GetKnowledgeBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeBaseRequest) ProtoMessage() {}

func (x *GetKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*GetKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{18}
}

func (x *GetKnowledgeBaseRequest) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

type GetKnowledgeBaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KnowledgeBase *KnowledgeBaseInfo `protobuf:"bytes,1,opt,name=knowledge_base,json=knowledgeBase,proto3" json:"knowledge_base,omitempty"`
}

func (x *GetKnowledgeBaseResponse) Reset() {
	*x = GetKnowledgeBaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knowledgebase_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKnowledgeBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeBaseResponse) ProtoMessage() {}

func (x *GetKnowledgeBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledgebase_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeBaseResponse.ProtoReflect.Descriptor instead.
func (*GetKnowledgeBaseResponse) Descriptor() ([]byte, []int) {
	return file_knowledgebase_proto_rawDescGZIP(), []int{19}
}

func (x *GetKnowledgeBaseResponse) GetKnowledgeBase() *KnowledgeBaseInfo {
	if x != nil {
		return x.KnowledgeBase
	}
	return nil
}

var File_knowledgebase_proto protoreflect.FileDescriptor

var file_knowledgebase_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x22, 0x4b,
	0x0a, 0x0b, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x21, 0x0a,
	0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72,
	0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x5f, 0x0a, 0x09, 0x44,
	0x6f, 0x63, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x64,
	0x6f, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x6f, 0x63,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xcc, 0x01, 0x0a,
	0x0b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x37, 0x0a, 0x0c, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x0b, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x89, 0x04, 0x0a, 0x11,
	0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x2a, 0x0a, 0x11, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x62,
	0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6b, 0x6e,
	0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x2a, 0x0a, 0x11, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f,
	0x77, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x2c, 0x0a,
	0x12, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x70, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x4f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x70, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x09, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x33,
	0x0a, 0x0a, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x13, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x53, 0x69, 0x6d,
	0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x37, 0x0a, 0x0c, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x75, 0x6d, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x0b, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2a, 0x0a, 0x11,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x75, 0x6d, 0x2e, 0x4b, 0x42, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x34, 0x0a, 0x09, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x7a, 0x65, 0x72,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d,
	0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x7a, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x7a, 0x65, 0x72, 0x12, 0x11, 0x0a, 0x04, 0x70, 0x71, 0x5f,
	0x6d, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x71, 0x4d, 0x12, 0x19, 0x0a, 0x08,
	0x70, 0x71, 0x5f, 0x6e, 0x62, 0x69, 0x74, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x70, 0x71, 0x4e, 0x62, 0x69, 0x74, 0x73, 0x22, 0x8f, 0x03, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x57, 0x69, 0x6e, 0x64,
	0x6f, 0x77, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f,
	0x6f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x70, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x10, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x4f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x70,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x75, 0x6d, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x73, 0x69, 0x6d, 0x69, 0x6c,
	0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79,
	0x52, 0x0a, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x37, 0x0a, 0x0c,
	0x65, 0x6d, 0x62, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x45, 0x6d, 0x62,
	0x65, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0b, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x34, 0x0a, 0x09, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x7a,
	0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x75, 0x6d, 0x2e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x7a, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x09, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x7a, 0x65, 0x72, 0x12, 0x11, 0x0a, 0x04, 0x70,
	0x71, 0x5f, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x71, 0x4d, 0x12, 0x19,
	0x0a, 0x08, 0x70, 0x71, 0x5f, 0x6e, 0x62, 0x69, 0x74, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x70, 0x71, 0x4e, 0x62, 0x69, 0x74, 0x73, 0x22, 0x77, 0x0a, 0x1b, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x6b, 0x6e, 0x6f, 0x77,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61,
	0x73, 0x65, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x10, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x22, 0x48, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2a, 0x0a, 0x11, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x62, 0x61,
	0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6b, 0x6e, 0x6f,
	0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x1b,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x9c, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a,
	0x0a, 0x11, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75,
	0x6d, 0x2e, 0x44, 0x6f, 0x63, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x73, 0x22, 0x36, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x13,
	0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x22,
	0x48, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x75, 0x6d, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x08, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x70, 0x0a, 0x16, 0x52, 0x6f, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12,
	0x2a, 0x0a, 0x11, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x17, 0x52,
	0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x22, 0x61, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x6b, 0x6e, 0x6f, 0x77,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61,
	0x73, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x1b, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x6e,
	0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x61, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x6e, 0x6f, 0x77, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x43, 0x0a, 0x0f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x62,
	0x61, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x75, 0x6d, 0x2e, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61,
	0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x42, 0x61, 0x73, 0x65, 0x73, 0x22, 0x45, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4b, 0x6e, 0x6f,
	0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2a, 0x0a, 0x11, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x62,
	0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6b, 0x6e,
	0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x22, 0x5d, 0x0a,
	0x18, 0x47, 0x65, 0x74, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x6b, 0x6e, 0x6f,
	0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x4b, 0x6e, 0x6f, 0x77,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x6b,
	0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x2a, 0x58, 0x0a, 0x0b,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x14, 0x49,
	0x4e, 0x44, 0x45, 0x58, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x45, 0x4e, 0x44,
	0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x44, 0x45, 0x58, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x01, 0x12, 0x17, 0x0a,
	0x13, 0x49, 0x4e, 0x44, 0x45, 0x58, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x41,
	0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x49, 0x0a, 0x09, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x4e, 0x44, 0x45, 0x58, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x48, 0x4e, 0x53, 0x57, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x44, 0x45,
	0x58, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x56, 0x46, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f,
	0x49, 0x4e, 0x44, 0x45, 0x58, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x4c, 0x41, 0x54, 0x10,
	0x02, 0x2a, 0x5b, 0x0a, 0x0a, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12,
	0x15, 0x0a, 0x11, 0x53, 0x49, 0x4d, 0x49, 0x4c, 0x41, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x43, 0x4f,
	0x53, 0x49, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x49, 0x4d, 0x49, 0x4c, 0x41,
	0x52, 0x49, 0x54, 0x59, 0x5f, 0x45, 0x55, 0x43, 0x4c, 0x49, 0x44, 0x45, 0x41, 0x4e, 0x10, 0x01,
	0x12, 0x1c, 0x0a, 0x18, 0x53, 0x49, 0x4d, 0x49, 0x4c, 0x41, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x49,
	0x4e, 0x4e, 0x45, 0x52, 0x5f, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43, 0x54, 0x10, 0x02, 0x2a, 0x75,
	0x0a, 0x0d, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x7a, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x11, 0x0a, 0x0d, 0x51, 0x55, 0x41, 0x4e, 0x54, 0x49, 0x5a, 0x45, 0x52, 0x5f, 0x4f, 0x46, 0x46,
	0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x51, 0x55, 0x41, 0x4e, 0x54, 0x49, 0x5a, 0x45, 0x52, 0x5f,
	0x53, 0x51, 0x38, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x51, 0x55, 0x41, 0x4e, 0x54, 0x49, 0x5a,
	0x45, 0x52, 0x5f, 0x53, 0x51, 0x5f, 0x42, 0x46, 0x31, 0x36, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11,
	0x51, 0x55, 0x41, 0x4e, 0x54, 0x49, 0x5a, 0x45, 0x52, 0x5f, 0x53, 0x51, 0x5f, 0x46, 0x50, 0x31,
	0x36, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x51, 0x55, 0x41, 0x4e, 0x54, 0x49, 0x5a, 0x45, 0x52,
	0x5f, 0x50, 0x51, 0x10, 0x04, 0x2a, 0x55, 0x0a, 0x08, 0x4b, 0x42, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x14, 0x0a, 0x10, 0x4b, 0x42, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41,
	0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x4b, 0x42, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12,
	0x1b, 0x0a, 0x17, 0x4b, 0x42, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x44, 0x45, 0x4c,
	0x45, 0x54, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x2a, 0x49, 0x0a, 0x08,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4f, 0x70, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x48, 0x41, 0x4e,
	0x47, 0x45, 0x5f, 0x4f, 0x50, 0x5f, 0x41, 0x44, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x43,
	0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x4f, 0x50, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10,
	0x01, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x4f, 0x50, 0x5f, 0x55,
	0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x02, 0x32, 0xd5, 0x05, 0x0a, 0x14, 0x4b, 0x6e, 0x6f, 0x77,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x60, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12, 0x23, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75,
	0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f,
	0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x60, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12, 0x23, 0x2e, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x75, 0x6d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b,
	0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x54, 0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x52,
	0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e,
	0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x75, 0x6d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75,
	0x6d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4b,
	0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x73, 0x12, 0x22, 0x2e,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x6e, 0x6f, 0x77,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4b, 0x6e, 0x6f,
	0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12, 0x20, 0x2e, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x75, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x1b, 0x5a, 0x19, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_knowledgebase_proto_rawDescOnce sync.Once
	file_knowledgebase_proto_rawDescData = file_knowledgebase_proto_rawDesc
)

func file_knowledgebase_proto_rawDescGZIP() []byte {
	file_knowledgebase_proto_rawDescOnce.Do(func() {
		file_knowledgebase_proto_rawDescData = protoimpl.X.CompressGZIP(file_knowledgebase_proto_rawDescData)
	})
	return file_knowledgebase_proto_rawDescData
}

var file_knowledgebase_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_knowledgebase_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_knowledgebase_proto_goTypes = []any{
	(IndexStatus)(0),                    // 0: stratum.IndexStatus
	(IndexType)(0),                      // 1: stratum.IndexType
	(Similarity)(0),                     // 2: stratum.Similarity
	(QuantizerType)(0),                  // 3: stratum.QuantizerType
	(KBStatus)(0),                       // 4: stratum.KBStatus
	(ChangeOp)(0),                       // 5: stratum.ChangeOp
	(*EmbedConfig)(nil),                 // 6: stratum.EmbedConfig
	(*DocChange)(nil),                   // 7: stratum.DocChange
	(*VersionInfo)(nil),                 // 8: stratum.VersionInfo
	(*KnowledgeBaseInfo)(nil),           // 9: stratum.KnowledgeBaseInfo
	(*CreateKnowledgeBaseRequest)(nil),  // 10: stratum.CreateKnowledgeBaseRequest
	(*CreateKnowledgeBaseResponse)(nil), // 11: stratum.CreateKnowledgeBaseResponse
	(*DeleteKnowledgeBaseRequest)(nil),  // 12: stratum.DeleteKnowledgeBaseRequest
	(*DeleteKnowledgeBaseResponse)(nil), // 13: stratum.DeleteKnowledgeBaseResponse
	(*CreateVersionRequest)(nil),        // 14: stratum.CreateVersionRequest
	(*CreateVersionResponse)(nil),       // 15: stratum.CreateVersionResponse
	(*ListVersionsRequest)(nil),         // 16: stratum.ListVersionsRequest
	(*ListVersionsResponse)(nil),        // 17: stratum.ListVersionsResponse
	(*RollbackVersionRequest)(nil),      // 18: stratum.RollbackVersionRequest
	(*RollbackVersionResponse)(nil),     // 19: stratum.RollbackVersionResponse
	(*DeleteVersionRequest)(nil),        // 20: stratum.DeleteVersionRequest
	(*DeleteVersionResponse)(nil),       // 21: stratum.DeleteVersionResponse
	(*ListKnowledgeBasesRequest)(nil),   // 22: stratum.ListKnowledgeBasesRequest
	(*ListKnowledgeBasesResponse)(nil),  // 23: stratum.ListKnowledgeBasesResponse
	(*GetKnowledgeBaseRequest)(nil),     // 24: stratum.GetKnowledgeBaseRequest
	(*GetKnowledgeBaseResponse)(nil),    // 25: stratum.GetKnowledgeBaseResponse
}
var file_knowledgebase_proto_depIdxs = []int32{
	5,  // 0: stratum.DocChange.op:type_name -> stratum.ChangeOp
	0,  // 1: stratum.VersionInfo.index_status:type_name -> stratum.IndexStatus
	1,  // 2: stratum.KnowledgeBaseInfo.index_type:type_name -> stratum.IndexType
	2,  // 3: stratum.KnowledgeBaseInfo.similarity:type_name -> stratum.Similarity
	6,  // 4: stratum.KnowledgeBaseInfo.embed_config:type_name -> stratum.EmbedConfig
	4,  // 5: stratum.KnowledgeBaseInfo.status:type_name -> stratum.KBStatus
	3,  // 6: stratum.KnowledgeBaseInfo.quantizer:type_name -> stratum.QuantizerType
	1,  // 7: stratum.CreateKnowledgeBaseRequest.index_type:type_name -> stratum.IndexType
	2,  // 8: stratum.CreateKnowledgeBaseRequest.similarity:type_name -> stratum.Similarity
	6,  // 9: stratum.CreateKnowledgeBaseRequest.embed_config:type_name -> stratum.EmbedConfig
	3,  // 10: stratum.CreateKnowledgeBaseRequest.quantizer:type_name -> stratum.QuantizerType
	7,  // 11: stratum.CreateVersionRequest.changes:type_name -> stratum.DocChange
	8,  // 12: stratum.ListVersionsResponse.versions:type_name -> stratum.VersionInfo
	9,  // 13: stratum.ListKnowledgeBasesResponse.knowledge_bases:type_name -> stratum.KnowledgeBaseInfo
	9,  // 14: stratum.GetKnowledgeBaseResponse.knowledge_base:type_name -> stratum.KnowledgeBaseInfo
	10, // 15: stratum.KnowledgeBaseService.CreateKnowledgeBase:input_type -> stratum.CreateKnowledgeBaseRequest
	12, // 16: stratum.KnowledgeBaseService.DeleteKnowledgeBase:input_type -> stratum.DeleteKnowledgeBaseRequest
	14, // 17: stratum.KnowledgeBaseService.CreateVersion:input_type -> stratum.CreateVersionRequest
	16, // 18: stratum.KnowledgeBaseService.ListVersions:input_type -> stratum.ListVersionsRequest
	18, // 19: stratum.KnowledgeBaseService.RollbackVersion:input_type -> stratum.RollbackVersionRequest
	20, // 20: stratum.KnowledgeBaseService.DeleteVersion:input_type -> stratum.DeleteVersionRequest
	22, // 21: stratum.KnowledgeBaseService.ListKnowledgeBases:input_type -> stratum.ListKnowledgeBasesRequest
	24, // 22: stratum.KnowledgeBaseService.GetKnowledgeBase:input_type -> stratum.GetKnowledgeBaseRequest
	11, // 23: stratum.KnowledgeBaseService.CreateKnowledgeBase:output_type -> stratum.CreateKnowledgeBaseResponse
	13, // 24: stratum.KnowledgeBaseService.DeleteKnowledgeBase:output_type -> stratum.DeleteKnowledgeBaseResponse
	15, // 25: stratum.KnowledgeBaseService.CreateVersion:output_type -> stratum.CreateVersionResponse
	17, // 26: stratum.KnowledgeBaseService.ListVersions:output_type -> stratum.ListVersionsResponse
	19, // 27: stratum.KnowledgeBaseService.RollbackVersion:output_type -> stratum.RollbackVersionResponse
	21, // 28: stratum.KnowledgeBaseService.DeleteVersion:output_type -> stratum.DeleteVersionResponse
	23, // 29: stratum.KnowledgeBaseService.ListKnowledgeBases:output_type -> stratum.ListKnowledgeBasesResponse
	25, // 30: stratum.KnowledgeBaseService.GetKnowledgeBase:output_type -> stratum.GetKnowledgeBaseResponse
	23, // [23:31] is the sub-list for method output_type
	15, // [15:23] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_knowledgebase_proto_init() }
func file_knowledgebase_proto_init() {
	if File_knowledgebase_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_knowledgebase_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EmbedConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DocChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*VersionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*KnowledgeBaseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreateKnowledgeBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CreateKnowledgeBaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteKnowledgeBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteKnowledgeBaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CreateVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CreateVersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ListVersionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ListVersionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*RollbackVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*RollbackVersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteVersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*ListKnowledgeBasesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*ListKnowledgeBasesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*GetKnowledgeBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knowledgebase_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*GetKnowledgeBaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_knowledgebase_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_knowledgebase_proto_goTypes,
		DependencyIndexes: file_knowledgebase_proto_depIdxs,
		EnumInfos:         file_knowledgebase_proto_enumTypes,
		MessageInfos:      file_knowledgebase_proto_msgTypes,
	}.Build()
	File_knowledgebase_proto = out.File
	file_knowledgebase_proto_rawDesc = nil
	file_knowledgebase_proto_goTypes = nil
	file_knowledgebase_proto_depIdxs = nil
}
