// sync.proto — internal DataSyncService: leader-to-follower data
// replication for the four PebbleDB/Vecstore layers that are NOT
// replicated via Raft.
//
// See Stratum_设计文档v10.md "多副本构建" and "索引异步构建".
//
// Synchronised layers:
//   - DocStore         (kbID + docID + versionID → content)
//   - ChunkDocMapper   (forward + reverse)
//   - VersionDocList   (kbID + versionID + docID)
//   - ChunkStore       (kbID + chunkID → vector)
//
// NOT synchronised (each replica builds independently):
//   - HNSW index           (via IndexManager.TriggerBuild)
//   - Chunk bloom filter   (from local chunk store)
//   - Version bloom filter (from local version doc list)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: sync.proto

package stratum

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataSyncService_ExecuteVersionWrite_FullMethodName = "/stratum.DataSyncService/ExecuteVersionWrite"
	DataSyncService_PullVersionData_FullMethodName     = "/stratum.DataSyncService/PullVersionData"
	DataSyncService_PullVersionChanges_FullMethodName  = "/stratum.DataSyncService/PullVersionChanges"
	DataSyncService_ReportDataVersions_FullMethodName  = "/stratum.DataSyncService/ReportDataVersions"
	DataSyncService_PushVersionData_FullMethodName     = "/stratum.DataSyncService/PushVersionData"
	DataSyncService_VersionPresence_FullMethodName     = "/stratum.DataSyncService/VersionPresence"
	DataSyncService_LocalVersion_FullMethodName        = "/stratum.DataSyncService/LocalVersion"
	DataSyncService_DeleteVersionData_FullMethodName   = "/stratum.DataSyncService/DeleteVersionData"
	DataSyncService_ConfirmVersionWrite_FullMethodName = "/stratum.DataSyncService/ConfirmVersionWrite"
	DataSyncService_PushIndexData_FullMethodName       = "/stratum.DataSyncService/PushIndexData"
)

// DataSyncServiceClient is the client API for DataSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataSyncService is an internal-only gRPC service for inter-node data
// replication. A node either pulls a version's records (server-side
// streaming) or is handed them by the version's write coordinator
// (client-side streaming) — the push direction is what lets a freshly
// written version reach its target replicas without waiting for them to
// notice it (Stratum_设计文档v13.md §7.2).
type DataSyncServiceClient interface {
	// ExecuteVersionWrite asks THIS node to run the storage-layer write
	// transaction for a version the control layer has already committed
	// (§7.13.2). The leader picks the coordinator from the knowledge base's
	// replica topology and dispatches the work here, so the data-plane cost
	// (split/embed/store locally, then fan out) lands on the coordinator rather
	// than on the control leader. Idempotent per (kb, version).
	ExecuteVersionWrite(ctx context.Context, in *ExecuteVersionWriteRequest, opts ...grpc.CallOption) (*ExecuteVersionWriteResponse, error)
	PullVersionData(ctx context.Context, in *PullVersionDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncEntry], error)
	// PullVersionChanges streams the recorded CHANGES for a range of versions, so a
	// node that is behind can replay the delta instead of pulling each version's
	// full record set (§7.5). The writer's WAL already holds them — the same BEGIN
	// record crash recovery replays — so this reads one store for a second purpose.
	//
	// Gaps are visible, not silent: a version with no record is simply not sent, and
	// the caller must fall back to a full state transfer rather than apply the range
	// as if those versions changed nothing.
	PullVersionChanges(ctx context.Context, in *PullVersionChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VersionChanges], error)
	// ReportDataVersions is the storage layer's periodic status report to the
	// control leader (§7.13.4): "for each knowledge base, my contiguous data cursor
	// has reached version N". The leader keeps the aggregate in memory and answers
	// "which nodes hold version V" from it — an authoritative view of where data
	// lives that is refreshed every interval, instead of a snapshot taken once and
	// stale from that moment on.
	//
	// accepted=false tells the reporter it reached a non-leader: it re-resolves the
	// leader and tries again next interval (§7.13.1's pattern), rather than the
	// system growing a second forwarding path.
	ReportDataVersions(ctx context.Context, in *ReportDataVersionsRequest, opts ...grpc.CallOption) (*ReportDataVersionsResponse, error)
	// PushVersionData hands one version's records to this node: the caller
	// (the write's coordinator) streams the same SyncEntry records
	// PullVersionData would have produced, and receives a single
	// acknowledgement once they have all been applied. Idempotent, like the
	// pull direction: records are keyed by (kb, version, doc/chunk).
	PushVersionData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SyncEntry, PushVersionDataResponse], error)
	// VersionPresence answers whether this node holds (kbID, versionID)'s data.
	// The control layer asks every candidate replica so it can tell a version
	// that is merely unbuilt from one whose data never landed anywhere
	// (Stratum_设计文档v13.md §7.12 step ① — the block-report union).
	VersionPresence(ctx context.Context, in *VersionPresenceRequest, opts ...grpc.CallOption) (*VersionPresenceResponse, error)
	// LocalVersion reports this node's contiguous data cursor for a knowledge
	// base: the highest version whose history it holds completely. A node that
	// is behind uses it to find a peer able to fill its gap instead of always
	// asking the leader (Stratum_设计文档v13.md §7.6).
	LocalVersion(ctx context.Context, in *LocalVersionRequest, opts ...grpc.CallOption) (*LocalVersionResponse, error)
	// DeleteVersionData reclaims a version's physical data on the receiving
	// node. The control layer broadcasts it to *every* candidate replica when it
	// declares a version FAILED_PERMANENT, because it does not know which
	// replicas actually landed the data (Stratum_设计文档v13.md §10.6).
	DeleteVersionData(ctx context.Context, in *DeleteVersionDataRequest, opts ...grpc.CallOption) (*DeleteVersionDataResponse, error)
	// ConfirmVersionWrite tells a replica that the version it received did reach
	// quorum, so the §7.3 takeover timer it started can stand down.
	ConfirmVersionWrite(ctx context.Context, in *ConfirmVersionWriteRequest, opts ...grpc.CallOption) (*ConfirmVersionWriteResponse, error)
	// PushIndexData streams one version's built index to a replica, so the
	// replica loads the artifact instead of rebuilding it: "建一次、分发 N 份"
	// (Stratum_设计文档v13.md §8.4). It replaces the "every replica builds its own
	// HNSW" premise, which also removed the build-collision defect where
	// several nodes ran Build (Reset + AddChunks) on the same version.
	PushIndexData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushIndexChunk, PushIndexDataResponse], error)
}

type dataSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataSyncServiceClient(cc grpc.ClientConnInterface) DataSyncServiceClient {
	return &dataSyncServiceClient{cc}
}

func (c *dataSyncServiceClient) ExecuteVersionWrite(ctx context.Context, in *ExecuteVersionWriteRequest, opts ...grpc.CallOption) (*ExecuteVersionWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteVersionWriteResponse)
	err := c.cc.Invoke(ctx, DataSyncService_ExecuteVersionWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSyncServiceClient) PullVersionData(ctx context.Context, in *PullVersionDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataSyncService_ServiceDesc.Streams[0], DataSyncService_PullVersionData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullVersionDataRequest, SyncEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSyncService_PullVersionDataClient = grpc.ServerStreamingClient[SyncEntry]

func (c *dataSyncServiceClient) PullVersionChanges(ctx context.Context, in *PullVersionChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VersionChanges], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataSyncService_ServiceDesc.Streams[1], DataSyncService_PullVersionChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullVersionChangesRequest, VersionChanges]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSyncService_PullVersionChangesClient = grpc.ServerStreamingClient[VersionChanges]

func (c *dataSyncServiceClient) ReportDataVersions(ctx context.Context, in *ReportDataVersionsRequest, opts ...grpc.CallOption) (*ReportDataVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportDataVersionsResponse)
	err := c.cc.Invoke(ctx, DataSyncService_ReportDataVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSyncServiceClient) PushVersionData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SyncEntry, PushVersionDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataSyncService_ServiceDesc.Streams[2], DataSyncService_PushVersionData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncEntry, PushVersionDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSyncService_PushVersionDataClient = grpc.ClientStreamingClient[SyncEntry, PushVersionDataResponse]

func (c *dataSyncServiceClient) VersionPresence(ctx context.Context, in *VersionPresenceRequest, opts ...grpc.CallOption) (*VersionPresenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionPresenceResponse)
	err := c.cc.Invoke(ctx, DataSyncService_VersionPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSyncServiceClient) LocalVersion(ctx context.Context, in *LocalVersionRequest, opts ...grpc.CallOption) (*LocalVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LocalVersionResponse)
	err := c.cc.Invoke(ctx, DataSyncService_LocalVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSyncServiceClient) DeleteVersionData(ctx context.Context, in *DeleteVersionDataRequest, opts ...grpc.CallOption) (*DeleteVersionDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVersionDataResponse)
	err := c.cc.Invoke(ctx, DataSyncService_DeleteVersionData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSyncServiceClient) ConfirmVersionWrite(ctx context.Context, in *ConfirmVersionWriteRequest, opts ...grpc.CallOption) (*ConfirmVersionWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmVersionWriteResponse)
	err := c.cc.Invoke(ctx, DataSyncService_ConfirmVersionWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSyncServiceClient) PushIndexData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushIndexChunk, PushIndexDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataSyncService_ServiceDesc.Streams[3], DataSyncService_PushIndexData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PushIndexChunk, PushIndexDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSyncService_PushIndexDataClient = grpc.ClientStreamingClient[PushIndexChunk, PushIndexDataResponse]

// DataSyncServiceServer is the server API for DataSyncService service.
// All implementations must embed UnimplementedDataSyncServiceServer
// for forward compatibility.
//
// DataSyncService is an internal-only gRPC service for inter-node data
// replication. A node either pulls a version's records (server-side
// streaming) or is handed them by the version's write coordinator
// (client-side streaming) — the push direction is what lets a freshly
// written version reach its target replicas without waiting for them to
// notice it (Stratum_设计文档v13.md §7.2).
type DataSyncServiceServer interface {
	// ExecuteVersionWrite asks THIS node to run the storage-layer write
	// transaction for a version the control layer has already committed
	// (§7.13.2). The leader picks the coordinator from the knowledge base's
	// replica topology and dispatches the work here, so the data-plane cost
	// (split/embed/store locally, then fan out) lands on the coordinator rather
	// than on the control leader. Idempotent per (kb, version).
	ExecuteVersionWrite(context.Context, *ExecuteVersionWriteRequest) (*ExecuteVersionWriteResponse, error)
	PullVersionData(*PullVersionDataRequest, grpc.ServerStreamingServer[SyncEntry]) error
	// PullVersionChanges streams the recorded CHANGES for a range of versions, so a
	// node that is behind can replay the delta instead of pulling each version's
	// full record set (§7.5). The writer's WAL already holds them — the same BEGIN
	// record crash recovery replays — so this reads one store for a second purpose.
	//
	// Gaps are visible, not silent: a version with no record is simply not sent, and
	// the caller must fall back to a full state transfer rather than apply the range
	// as if those versions changed nothing.
	PullVersionChanges(*PullVersionChangesRequest, grpc.ServerStreamingServer[VersionChanges]) error
	// ReportDataVersions is the storage layer's periodic status report to the
	// control leader (§7.13.4): "for each knowledge base, my contiguous data cursor
	// has reached version N". The leader keeps the aggregate in memory and answers
	// "which nodes hold version V" from it — an authoritative view of where data
	// lives that is refreshed every interval, instead of a snapshot taken once and
	// stale from that moment on.
	//
	// accepted=false tells the reporter it reached a non-leader: it re-resolves the
	// leader and tries again next interval (§7.13.1's pattern), rather than the
	// system growing a second forwarding path.
	ReportDataVersions(context.Context, *ReportDataVersionsRequest) (*ReportDataVersionsResponse, error)
	// PushVersionData hands one version's records to this node: the caller
	// (the write's coordinator) streams the same SyncEntry records
	// PullVersionData would have produced, and receives a single
	// acknowledgement once they have all been applied. Idempotent, like the
	// pull direction: records are keyed by (kb, version, doc/chunk).
	PushVersionData(grpc.ClientStreamingServer[SyncEntry, PushVersionDataResponse]) error
	// VersionPresence answers whether this node holds (kbID, versionID)'s data.
	// The control layer asks every candidate replica so it can tell a version
	// that is merely unbuilt from one whose data never landed anywhere
	// (Stratum_设计文档v13.md §7.12 step ① — the block-report union).
	VersionPresence(context.Context, *VersionPresenceRequest) (*VersionPresenceResponse, error)
	// LocalVersion reports this node's contiguous data cursor for a knowledge
	// base: the highest version whose history it holds completely. A node that
	// is behind uses it to find a peer able to fill its gap instead of always
	// asking the leader (Stratum_设计文档v13.md §7.6).
	LocalVersion(context.Context, *LocalVersionRequest) (*LocalVersionResponse, error)
	// DeleteVersionData reclaims a version's physical data on the receiving
	// node. The control layer broadcasts it to *every* candidate replica when it
	// declares a version FAILED_PERMANENT, because it does not know which
	// replicas actually landed the data (Stratum_设计文档v13.md §10.6).
	DeleteVersionData(context.Context, *DeleteVersionDataRequest) (*DeleteVersionDataResponse, error)
	// ConfirmVersionWrite tells a replica that the version it received did reach
	// quorum, so the §7.3 takeover timer it started can stand down.
	ConfirmVersionWrite(context.Context, *ConfirmVersionWriteRequest) (*ConfirmVersionWriteResponse, error)
	// PushIndexData streams one version's built index to a replica, so the
	// replica loads the artifact instead of rebuilding it: "建一次、分发 N 份"
	// (Stratum_设计文档v13.md §8.4). It replaces the "every replica builds its own
	// HNSW" premise, which also removed the build-collision defect where
	// several nodes ran Build (Reset + AddChunks) on the same version.
	PushIndexData(grpc.ClientStreamingServer[PushIndexChunk, PushIndexDataResponse]) error
	mustEmbedUnimplementedDataSyncServiceServer()
}

// UnimplementedDataSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataSyncServiceServer struct{}

func (UnimplementedDataSyncServiceServer) ExecuteVersionWrite(context.Context, *ExecuteVersionWriteRequest) (*ExecuteVersionWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteVersionWrite not implemented")
}
func (UnimplementedDataSyncServiceServer) PullVersionData(*PullVersionDataRequest, grpc.ServerStreamingServer[SyncEntry]) error {
	return status.Errorf(codes.Unimplemented, "method PullVersionData not implemented")
}
func (UnimplementedDataSyncServiceServer) PullVersionChanges(*PullVersionChangesRequest, grpc.ServerStreamingServer[VersionChanges]) error {
	return status.Errorf(codes.Unimplemented, "method PullVersionChanges not implemented")
}
func (UnimplementedDataSyncServiceServer) ReportDataVersions(context.Context, *ReportDataVersionsRequest) (*ReportDataVersionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportDataVersions not implemented")
}
func (UnimplementedDataSyncServiceServer) PushVersionData(grpc.ClientStreamingServer[SyncEntry, PushVersionDataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PushVersionData not implemented")
}
func (UnimplementedDataSyncServiceServer) VersionPresence(context.Context, *VersionPresenceRequest) (*VersionPresenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VersionPresence not implemented")
}
func (UnimplementedDataSyncServiceServer) LocalVersion(context.Context, *LocalVersionRequest) (*LocalVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LocalVersion not implemented")
}
func (UnimplementedDataSyncServiceServer) DeleteVersionData(context.Context, *DeleteVersionDataRequest) (*DeleteVersionDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVersionData not implemented")
}
func (UnimplementedDataSyncServiceServer) ConfirmVersionWrite(context.Context, *ConfirmVersionWriteRequest) (*ConfirmVersionWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmVersionWrite not implemented")
}
func (UnimplementedDataSyncServiceServer) PushIndexData(grpc.ClientStreamingServer[PushIndexChunk, PushIndexDataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PushIndexData not implemented")
}
func (UnimplementedDataSyncServiceServer) mustEmbedUnimplementedDataSyncServiceServer() {}
func (UnimplementedDataSyncServiceServer) testEmbeddedByValue()                         {}

// UnsafeDataSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataSyncServiceServer will
// result in compilation errors.
type UnsafeDataSyncServiceServer interface {
	mustEmbedUnimplementedDataSyncServiceServer()
}

func RegisterDataSyncServiceServer(s grpc.ServiceRegistrar, srv DataSyncServiceServer) {
	// If the following call pancis, it indicates UnimplementedDataSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataSyncService_ServiceDesc, srv)
}

func _DataSyncService_ExecuteVersionWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteVersionWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSyncServiceServer).ExecuteVersionWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSyncService_ExecuteVersionWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSyncServiceServer).ExecuteVersionWrite(ctx, req.(*ExecuteVersionWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSyncService_PullVersionData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullVersionDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataSyncServiceServer).PullVersionData(m, &grpc.GenericServerStream[PullVersionDataRequest, SyncEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSyncService_PullVersionDataServer = grpc.ServerStreamingServer[SyncEntry]

func _DataSyncService_PullVersionChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullVersionChangesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataSyncServiceServer).PullVersionChanges(m, &grpc.GenericServerStream[PullVersionChangesRequest, VersionChanges]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSyncService_PullVersionChangesServer = grpc.ServerStreamingServer[VersionChanges]

func _DataSyncService_ReportDataVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportDataVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSyncServiceServer).ReportDataVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSyncService_ReportDataVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSyncServiceServer).ReportDataVersions(ctx, req.(*ReportDataVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSyncService_PushVersionData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataSyncServiceServer).PushVersionData(&grpc.GenericServerStream[SyncEntry, PushVersionDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSyncService_PushVersionDataServer = grpc.ClientStreamingServer[SyncEntry, PushVersionDataResponse]

func _DataSyncService_VersionPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSyncServiceServer).VersionPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSyncService_VersionPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSyncServiceServer).VersionPresence(ctx, req.(*VersionPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSyncService_LocalVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocalVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSyncServiceServer).LocalVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSyncService_LocalVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSyncServiceServer).LocalVersion(ctx, req.(*LocalVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSyncService_DeleteVersionData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVersionDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSyncServiceServer).DeleteVersionData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSyncService_DeleteVersionData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSyncServiceServer).DeleteVersionData(ctx, req.(*DeleteVersionDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSyncService_ConfirmVersionWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmVersionWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSyncServiceServer).ConfirmVersionWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSyncService_ConfirmVersionWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSyncServiceServer).ConfirmVersionWrite(ctx, req.(*ConfirmVersionWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSyncService_PushIndexData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataSyncServiceServer).PushIndexData(&grpc.GenericServerStream[PushIndexChunk, PushIndexDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSyncService_PushIndexDataServer = grpc.ClientStreamingServer[PushIndexChunk, PushIndexDataResponse]

// DataSyncService_ServiceDesc is the grpc.ServiceDesc for DataSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stratum.DataSyncService",
	HandlerType: (*DataSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteVersionWrite",
			Handler:    _DataSyncService_ExecuteVersionWrite_Handler,
		},
		{
			MethodName: "ReportDataVersions",
			Handler:    _DataSyncService_ReportDataVersions_Handler,
		},
		{
			MethodName: "VersionPresence",
			Handler:    _DataSyncService_VersionPresence_Handler,
		},
		{
			MethodName: "LocalVersion",
			Handler:    _DataSyncService_LocalVersion_Handler,
		},
		{
			MethodName: "DeleteVersionData",
			Handler:    _DataSyncService_DeleteVersionData_Handler,
		},
		{
			MethodName: "ConfirmVersionWrite",
			Handler:    _DataSyncService_ConfirmVersionWrite_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullVersionData",
			Handler:       _DataSyncService_PullVersionData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PullVersionChanges",
			Handler:       _DataSyncService_PullVersionChanges_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PushVersionData",
			Handler:       _DataSyncService_PushVersionData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PushIndexData",
			Handler:       _DataSyncService_PushIndexData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sync.proto",
}
