// sync.proto — internal DataSyncService: leader-to-follower data
// replication for the four PebbleDB/Vecstore layers that are NOT
// replicated via Raft.
//
// See Stratum_设计文档v10.md "多副本构建" and "索引异步构建".
//
// Synchronised layers:
//   - DocStore         (kbID + docID + versionID → content)
//   - ChunkDocMapper   (forward + reverse)
//   - VersionDocList   (kbID + versionID + docID)
//   - ChunkStore       (kbID + chunkID → vector)
//
// NOT synchronised (each replica builds independently):
//   - HNSW index           (via IndexManager.TriggerBuild)
//   - Chunk bloom filter   (from local chunk store)
//   - Version bloom filter (from local version doc list)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/sync.proto

package stratum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncEntryType int32

const (
	SyncEntryType_SYNC_ENTRY_TYPE_UNSPECIFIED       SyncEntryType = 0
	SyncEntryType_SYNC_ENTRY_TYPE_DOC_STORE         SyncEntryType = 1 // kb_id + doc_id + version_id + payload
	SyncEntryType_SYNC_ENTRY_TYPE_CHUNK_DOC_FORWARD SyncEntryType = 2 // kb_id + chunk_id + doc_id
	SyncEntryType_SYNC_ENTRY_TYPE_CHUNK_DOC_REVERSE SyncEntryType = 3 // kb_id + doc_id + chunk_id
	SyncEntryType_SYNC_ENTRY_TYPE_VERSION_DOC_LIST  SyncEntryType = 4 // kb_id + version_id + doc_id
	SyncEntryType_SYNC_ENTRY_TYPE_CHUNK_VECTOR      SyncEntryType = 5 // kb_id + chunk_id + payload (float32 vector)
)

// Enum value maps for SyncEntryType.
var (
	SyncEntryType_name = map[int32]string{
		0: "SYNC_ENTRY_TYPE_UNSPECIFIED",
		1: "SYNC_ENTRY_TYPE_DOC_STORE",
		2: "SYNC_ENTRY_TYPE_CHUNK_DOC_FORWARD",
		3: "SYNC_ENTRY_TYPE_CHUNK_DOC_REVERSE",
		4: "SYNC_ENTRY_TYPE_VERSION_DOC_LIST",
		5: "SYNC_ENTRY_TYPE_CHUNK_VECTOR",
	}
	SyncEntryType_value = map[string]int32{
		"SYNC_ENTRY_TYPE_UNSPECIFIED":       0,
		"SYNC_ENTRY_TYPE_DOC_STORE":         1,
		"SYNC_ENTRY_TYPE_CHUNK_DOC_FORWARD": 2,
		"SYNC_ENTRY_TYPE_CHUNK_DOC_REVERSE": 3,
		"SYNC_ENTRY_TYPE_VERSION_DOC_LIST":  4,
		"SYNC_ENTRY_TYPE_CHUNK_VECTOR":      5,
	}
)

func (x SyncEntryType) Enum() *SyncEntryType {
	p := new(SyncEntryType)
	*p = x
	return p
}

func (x SyncEntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncEntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_sync_proto_enumTypes[0].Descriptor()
}

func (SyncEntryType) Type() protoreflect.EnumType {
	return &file_api_proto_sync_proto_enumTypes[0]
}

func (x SyncEntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncEntryType.Descriptor instead.
func (SyncEntryType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{0}
}

type PullVersionDataRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeBaseId string                 `protobuf:"bytes,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
	VersionId       int64                  `protobuf:"varint,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PullVersionDataRequest) Reset() {
	*x = PullVersionDataRequest{}
	mi := &file_api_proto_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullVersionDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullVersionDataRequest) ProtoMessage() {}

func (x *PullVersionDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullVersionDataRequest.ProtoReflect.Descriptor instead.
func (*PullVersionDataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{0}
}

func (x *PullVersionDataRequest) GetKnowledgeBaseId() string {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return ""
}

func (x *PullVersionDataRequest) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

// SyncEntry is one record in the stream. The entry_type field determines
// which storage layer the record belongs to.
type SyncEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryType     SyncEntryType          `protobuf:"varint,1,opt,name=entry_type,json=entryType,proto3,enum=stratum.SyncEntryType" json:"entry_type,omitempty"`
	KbId          string                 `protobuf:"bytes,2,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	DocId         string                 `protobuf:"bytes,3,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	ChunkId       string                 `protobuf:"bytes,4,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	VersionId     int64                  `protobuf:"varint,5,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"` // doc text (DOC_STORE), vector (CHUNK_VECTOR), or empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncEntry) Reset() {
	*x = SyncEntry{}
	mi := &file_api_proto_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEntry) ProtoMessage() {}

func (x *SyncEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEntry.ProtoReflect.Descriptor instead.
func (*SyncEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncEntry) GetEntryType() SyncEntryType {
	if x != nil {
		return x.EntryType
	}
	return SyncEntryType_SYNC_ENTRY_TYPE_UNSPECIFIED
}

func (x *SyncEntry) GetKbId() string {
	if x != nil {
		return x.KbId
	}
	return ""
}

func (x *SyncEntry) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *SyncEntry) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *SyncEntry) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *SyncEntry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_api_proto_sync_proto protoreflect.FileDescriptor

const file_api_proto_sync_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/sync.proto\x12\astratum\"c\n" +
	"\x16PullVersionDataRequest\x12*\n" +
	"\x11knowledge_base_id\x18\x01 \x01(\tR\x0fknowledgeBaseId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\x03R\tversionId\"\xc2\x01\n" +
	"\tSyncEntry\x125\n" +
	"\n" +
	"entry_type\x18\x01 \x01(\x0e2\x16.stratum.SyncEntryTypeR\tentryType\x12\x13\n" +
	"\x05kb_id\x18\x02 \x01(\tR\x04kbId\x12\x15\n" +
	"\x06doc_id\x18\x03 \x01(\tR\x05docId\x12\x19\n" +
	"\bchunk_id\x18\x04 \x01(\tR\achunkId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x05 \x01(\x03R\tversionId\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload*\xe5\x01\n" +
	"\rSyncEntryType\x12\x1f\n" +
	"\x1bSYNC_ENTRY_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SYNC_ENTRY_TYPE_DOC_STORE\x10\x01\x12%\n" +
	"!SYNC_ENTRY_TYPE_CHUNK_DOC_FORWARD\x10\x02\x12%\n" +
	"!SYNC_ENTRY_TYPE_CHUNK_DOC_REVERSE\x10\x03\x12$\n" +
	" SYNC_ENTRY_TYPE_VERSION_DOC_LIST\x10\x04\x12 \n" +
	"\x1cSYNC_ENTRY_TYPE_CHUNK_VECTOR\x10\x052[\n" +
	"\x0fDataSyncService\x12H\n" +
	"\x0fPullVersionData\x12\x1f.stratum.PullVersionDataRequest\x1a\x12.stratum.SyncEntry0\x01B\x1bZ\x19stratum/api/proto/stratumb\x06proto3"

var (
	file_api_proto_sync_proto_rawDescOnce sync.Once
	file_api_proto_sync_proto_rawDescData []byte
)

func file_api_proto_sync_proto_rawDescGZIP() []byte {
	file_api_proto_sync_proto_rawDescOnce.Do(func() {
		file_api_proto_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_sync_proto_rawDesc), len(file_api_proto_sync_proto_rawDesc)))
	})
	return file_api_proto_sync_proto_rawDescData
}

var file_api_proto_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_sync_proto_goTypes = []any{
	(SyncEntryType)(0),             // 0: stratum.SyncEntryType
	(*PullVersionDataRequest)(nil), // 1: stratum.PullVersionDataRequest
	(*SyncEntry)(nil),              // 2: stratum.SyncEntry
}
var file_api_proto_sync_proto_depIdxs = []int32{
	0, // 0: stratum.SyncEntry.entry_type:type_name -> stratum.SyncEntryType
	1, // 1: stratum.DataSyncService.PullVersionData:input_type -> stratum.PullVersionDataRequest
	2, // 2: stratum.DataSyncService.PullVersionData:output_type -> stratum.SyncEntry
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_sync_proto_init() }
func file_api_proto_sync_proto_init() {
	if File_api_proto_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_sync_proto_rawDesc), len(file_api_proto_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_sync_proto_goTypes,
		DependencyIndexes: file_api_proto_sync_proto_depIdxs,
		EnumInfos:         file_api_proto_sync_proto_enumTypes,
		MessageInfos:      file_api_proto_sync_proto_msgTypes,
	}.Build()
	File_api_proto_sync_proto = out.File
	file_api_proto_sync_proto_goTypes = nil
	file_api_proto_sync_proto_depIdxs = nil
}
