// sync.proto — internal DataSyncService: leader-to-follower data
// replication for the four PebbleDB/Vecstore layers that are NOT
// replicated via Raft.
//
// See Stratum_设计文档v10.md "多副本构建" and "索引异步构建".
//
// Synchronised layers:
//   - DocStore         (kbID + docID + versionID → content)
//   - ChunkDocMapper   (forward + reverse)
//   - VersionDocList   (kbID + versionID + docID)
//   - ChunkStore       (kbID + chunkID → vector)
//
// NOT synchronised (each replica builds independently):
//   - HNSW index           (via IndexManager.TriggerBuild)
//   - Chunk bloom filter   (from local chunk store)
//   - Version bloom filter (from local version doc list)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/proto/sync.proto

package stratum

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataSyncService_PullVersionData_FullMethodName = "/stratum.DataSyncService/PullVersionData"
)

// DataSyncServiceClient is the client API for DataSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DataSyncService is an internal-only gRPC service for leader→follower
// data pull. Followers open a server-side streaming RPC per version and
// apply each SyncEntry to their local storage layers.
type DataSyncServiceClient interface {
	PullVersionData(ctx context.Context, in *PullVersionDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncEntry], error)
}

type dataSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataSyncServiceClient(cc grpc.ClientConnInterface) DataSyncServiceClient {
	return &dataSyncServiceClient{cc}
}

func (c *dataSyncServiceClient) PullVersionData(ctx context.Context, in *PullVersionDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataSyncService_ServiceDesc.Streams[0], DataSyncService_PullVersionData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PullVersionDataRequest, SyncEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSyncService_PullVersionDataClient = grpc.ServerStreamingClient[SyncEntry]

// DataSyncServiceServer is the server API for DataSyncService service.
// All implementations must embed UnimplementedDataSyncServiceServer
// for forward compatibility.
//
// DataSyncService is an internal-only gRPC service for leader→follower
// data pull. Followers open a server-side streaming RPC per version and
// apply each SyncEntry to their local storage layers.
type DataSyncServiceServer interface {
	PullVersionData(*PullVersionDataRequest, grpc.ServerStreamingServer[SyncEntry]) error
	mustEmbedUnimplementedDataSyncServiceServer()
}

// UnimplementedDataSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataSyncServiceServer struct{}

func (UnimplementedDataSyncServiceServer) PullVersionData(*PullVersionDataRequest, grpc.ServerStreamingServer[SyncEntry]) error {
	return status.Error(codes.Unimplemented, "method PullVersionData not implemented")
}
func (UnimplementedDataSyncServiceServer) mustEmbedUnimplementedDataSyncServiceServer() {}
func (UnimplementedDataSyncServiceServer) testEmbeddedByValue()                         {}

// UnsafeDataSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataSyncServiceServer will
// result in compilation errors.
type UnsafeDataSyncServiceServer interface {
	mustEmbedUnimplementedDataSyncServiceServer()
}

func RegisterDataSyncServiceServer(s grpc.ServiceRegistrar, srv DataSyncServiceServer) {
	// If the following call panics, it indicates UnimplementedDataSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataSyncService_ServiceDesc, srv)
}

func _DataSyncService_PullVersionData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullVersionDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataSyncServiceServer).PullVersionData(m, &grpc.GenericServerStream[PullVersionDataRequest, SyncEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSyncService_PullVersionDataServer = grpc.ServerStreamingServer[SyncEntry]

// DataSyncService_ServiceDesc is the grpc.ServiceDesc for DataSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stratum.DataSyncService",
	HandlerType: (*DataSyncServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PullVersionData",
			Handler:       _DataSyncService_PullVersionData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/sync.proto",
}
